<?php
$ssFilter = $this->ssFilter;
$currentController = $this->layout()->controller;

// CREATE INPUT HIDDEN
$inputHiddenOrder = $this->ocoderFormHidden('order', $ssFilter['order']);
$inputHiddenOrderBy = $this->ocoderFormHidden('order_by', $ssFilter['order_by']);
$inputpublishedID = $this->ocoderFormHidden('published_id', null);
$inputpublishedValue = $this->ocoderFormHidden('published_value', null);
$strInputHidden = $inputHiddenOrder . $inputHiddenOrderBy . $inputpublishedID . $inputpublishedValue;

// CREATE SELECTBOX
$arrKeywordType = array('username' => 'Search by USERNAME', 'id' => 'Search by ID', 'email' => 'Search by EMAIL', 'all' => 'Search by ALL');
//$slbKeywordType 	= $this->ocoderFormSelect('filter_keyword_type', null , $arrKeywordType, $ssFilter['filter_keyword_type']);
$slbFilterpublished = $this->ocoderFormSelect('filter_published', '-- ' . PUBLISHED . ' --', array('active' => ACTIVE, 'inactive' => INACTIVE), $ssFilter['filter_published']);
// CREATE INPUT
$inputKeyword = $this->ocoderFormInput('filter_keyword_value', $ssFilter['filter_keyword_value'], array('class' => 'form-control input-sm'));
// CREATE BUTTON
$btnClear = $this->ocoderFormButton('btn-clear', 'btn-clear', CLEAR, array('class' => 'btn-default'));
$btnSearch = $this->ocoderFormButton('btn-go', 'btn-go', SEARCH, array('class' => 'btn-primary'));

$linkAdd = $this->cmsLinkAdmin(array('controller' => $currentController, 'action' => 'form'));
// DATA ITEM
$xhtmlItems = '';
if (!empty($this->items)) {
    foreach ($this->items as $item) {
        $class = $this->cycle(array('odd', 'even'))->next();
        $id = $item->id;
        $username = $item->username;
        $email = $item->email;
        $avatar = $item->avatar;
        $fullname = $item->fullname;
        $published = $this->CmsButtonPublished($id, $item->published);
        $cid = $this->ocoderFormInput('cid[]', $id, array('type' => 'checkbox'));
        $linkEdit = $this->cmsLinkAdmin(array('controller' => $currentController, 'action' => 'form', 'id' => $id));
        $xhtmlItems .= '<tr class="' . $class . '">
                            <td>' . $cid . '</td>
                            <td>' . $this->cmsInfoUser($avatar, $linkEdit, $username, $fullname) . '</td>
                            <td>' . $email . '</td>
                            <td>' . $published . '</td>
                            <td>' . $id . '</td>
                        </tr>';
    }
}
// LINK FORM SUBMIT
$linkFormSubmit = $this->cmsLinkAdmin(array('controller' => $currentController, 'action' => 'filter'));
?>
<section class="content-header">
    <h1>
        <?php echo USER_MANAGEMENT ?>
        <small><?php echo LISTS ?></small>
    </h1>
</section>
<!-- Main content -->
<section class="content">
    <!-- BUTTON -->
    <div class="row">
        <div class="text-center">
            <!--<a data-type="show-total" class="btn btn-app" href="#" onclick="javascript:changeOrdering();"><i class="fa fa-refresh"></i><?php echo UPDATE ?></a>--> 
            <a class="btn btn-app" href="<?php echo $linkAdd; ?>"><i class="fa fa-plus-square-o"></i> <?php echo ADD ?></a> 
<!--            <a data-type="show-total" class="btn btn-app" href="#" onclick="javascript:changemultiPublished(1);"><i class="fa fa-check-circle-o"></i> <?php echo ACTIVE ?></a>
            <a data-type="show-total" class="btn btn-app" href="#" onclick="javascript:changemultiPublished(0);"><i class="fa fa-circle-o"></i> <?php echo INACTIVE ?></a> -->
            <a data-type="show-total" class="btn btn-app" href="#" onclick="javascript:deleteItem('<?php echo CONFIRM_DELETE; ?>', '<?php echo NO_ITEMS_CHOOSE; ?>')"><i class="fa fa-minus-square-o"></i> <?php echo DELETE ?></a>
        </div>
    </div>
    <!-- NOTICE -->
    <?php 
    echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); 
    echo $this->flashMessenger()->render('error', array('alert', 'alert-danger')); 
    ?>
    <?php ?>
    <div class="box box-info">	
        <form name="adminForm" id="adminForm" action="<?php echo $linkFormSubmit; ?>" method="post">
            <div class="box-body table-responsive">
                <div class="dataTables_wrapper" role="grid">
                    <table class="table table-bordered table-striped dataTable text-center">
                        <!-- COLUMN TITLE -->
                        <thead>
                            <tr role="row">
                                <th class="col-sm-1"><input type="checkbox" id="check-all" /></th>
                                <?php echo $this->cmsLinkSort(USERNAME, 'username', $ssFilter, array('class' => 'col-sm-4')); ?>
                                <?php echo $this->cmsLinkSort(EMAIL, 'email', $ssFilter, array('class' => 'col-sm-4')); ?>
                                <?php echo $this->cmsLinkSort(PUBLISHED, 'published', $ssFilter, array('class' => 'col-sm-2')); ?>
                                <?php echo $this->cmsLinkSort(ID, 'id', $ssFilter, array('class' => 'col-sm-1')); ?>
                            </tr>
                        </thead>

                        <!-- CONTENT TABLE -->
                        <tbody><?php echo $xhtmlItems; ?></tbody>
                    </table>

                    <!-- PAGINATION -->
                    <?php
                    if(count($this->items) > 0){
                        $currentURL = $this->cmsLinkAdmin(array('controller' => $currentController, 'action' => 'index'));
                        echo $this->paginationControl($this->paginator, 'sliding', 'paginator.phtml', array('currentURL' => $currentURL));
                    }
                    ?>
                </div>
            </div>
            <!-- INPUT HIDDEN -->
            <?php echo $strInputHidden; ?>
        </form>
    </div>
</section><!-- /.content -->