<p>
    <strong><?php echo TRAFFIC_REPORT ?>:</strong> 
    <?php echo TODAY . ': ' . $this->today ?> - 
    <?php echo YESTERDAY . ': ' . $this->yesterday ?> - 
    <?php echo CURRENT_WEEK . ': ' . $this->currentWeek ?> - 
    <?php echo PREVIOUS_WEEK . ': ' . $this->previousWeek ?> - 
    <?php echo PREVIOUS_MONTH . ': ' . $this->previousMonth ?> - 
    <?php echo TOTAL . ': ' . $this->total ?>
</p>