<?php $userInfo = $this->_data; ?>
<li class="dropdown user user-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="glyphicon glyphicon-user"></i>
        <span><?php echo $userInfo->fullname ?> <i class="caret"></i></span>
    </a>
    <ul class="dropdown-menu">
        <!-- User image -->
        <li class="user-header bg-light-blue">
            <img src="<?php echo URL_PUBLIC . '/img/avatar.png' ?>" class="img-circle" alt="User Image">
            <p>
                <?php echo $userInfo->fullname ?>
                <small><?php echo $userInfo->email ?></small>
            </p>
        </li>
        <!-- Menu Body -->
        <!--<li class="user-body">
            <div class="col-xs-4 text-center">
                <a href="#">Followers</a>
            </div>
            <div class="col-xs-4 text-center">
                <a href="#">Sales</a>
            </div>
            <div class="col-xs-4 text-center">
                <a href="#">Friends</a>
            </div>
        </li>-->
        <!-- Menu Footer-->
        <li class="user-footer">
            <div class="pull-left">
                <a href="<?php echo URL_APPLICATION . '/admin/user/form/' . $userInfo->id ?>" class="btn btn-default btn-flat"><?php echo PROFILE ?></a>
            </div>
            <div class="pull-right">
                <a href="<?php echo URL_APPLICATION . '/admin/account/logout' ?>" class="btn btn-default btn-flat"><?php echo SIGN_OUT ?></a>
            </div>
        </li>
    </ul>
</li>