<!-- Partners Blocks -->
<div class="row partners">
    <div class="col-md-12">
        <?php echo $this->blkPartners(); ?>
    </div>
</div><!-- END Partners Blocks -->

<!-- Footer of website -->
<footer class="row">
    <div class="menu-bottom col-md-12">
        <ul class="list-unstyled list-inline">
            <li><a href="<?php echo URL_APPLICATION ?>"><?php echo HOME ?></a></li>
            <li><a href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_INTRO ?>"><?php echo COMPANY ?></a></li>
            <li><a href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_PRODUCTS ?>"><?php echo PRODUCT ?></a></li>
            <li><a href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_SERVICE ?>"><?php echo SERVICES ?></a></li>
            <li><a href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_NEWS ?>"><?php echo NEWS ?></a></li>
            <li><a href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_RECRUITMENT ?>"><?php echo RECRUITMENT ?></a></li>
            <li><a href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_CONTACT ?>"><?php echo CONTACT ?></a></li>
        </ul>
        <!-- |
        <a rel="nofollow" href="#">Giới thiệu</a>|
        <a rel="nofollow" href="#">Đăng ký <strong>Trang Doanh Nghiệp</strong></a>|
        <a rel="nofollow" href="#">Gian hàng <strong>Trang Doanh Nghiệp</strong></a>|
        <a rel="nofollow" href="#">Quảng cáo <strong>Trang Doanh Nghiệp</strong></a>|
        <a rel="nofollow" href="#">Liên hệ</a>|
        <a target="_blank" href="#">ENGLISH</a> -->
    </div>
    <?php echo $this->blkTrafic(); ?>
    <div class="copyright col-md-12">
        Copyright © 2015 <strong>Phú An Phát</strong> Việt Nam. All rights reserved.
    </div>
</footer>

<script type="text/javascript">

    function clip() {
        // width of the banner container
        var contWidth = 1000;
        // height of the banner container
        var contHeight = 90;

        var id1 = document.getElementById('slideA');
        var id2 = document.getElementById('slideB');

        id1.style.left = parseInt(id1.style.left) - 1 + 'px';

        document.getElementById('slideCont').style.width = contWidth + "px";
        document.getElementById('slideCont').style.clip = 'rect(auto,' + contWidth + 'px,' + contHeight + 'px,auto)';
        id2.style.display = '';
        if (parseFloat(id1.style.left) == -(contWidth)) {
            id1.style.left = '0px';
        }
        setTimeout(clip, 25)
    }

    function addLoadEvent(func) {
        var oldonload = window.onload;
        if (typeof window.onload != 'function') {
            window.onload = func;
        } else {
            window.onload = function () {
                if (oldonload) {
                    oldonload();
                }
                func();
            }
        }
    }

    addLoadEvent(function () {
        clip();
    });
    //-->
</script>