<?php

use Zend\Session\Container;

$ssSystem = new Container('system');
$helperString = new \Ocoder\Helper\String;
$StrUrl=$helperString->getCurrentUrl();
$chuoi=explode('-', $StrUrl);
$check=end($chuoi);
?>


<div class="col_left">
    <div id="posoffset"></div>
    <ul class="Category">
            <?php
            foreach ($this->_data as $item) {
                $Id=$item->id;
                if ($ssSystem->language == DEFAULT_LANGUAGE) {
                    $name = $item->name;
                    $alias = $item->alias;
                } else {
                    $nameLang = json_decode($item->name_lang);
                    $nameField = 'name_' . $ssSystem->language;
                    $name = $nameLang->$nameField;
                    $aliasLang = json_decode($item->alias_lang);
                    $aliasField = 'alias_' . $ssSystem->language;
                    $alias = $aliasLang->$aliasField;
                }
            ?>
         <?php if ($Id==$check){?>
                <li class="CategoryChild active"><a href="<?php echo URL_APPLICATION . '/bv/' . $alias ?>"><?php echo  $name ?></a></li>
        <?php } else { ?>
            <li class="CategoryChild "><a href="<?php echo URL_APPLICATION . '/bv/' . $alias ?>"><?php echo  $name ?></a></li>
           
        <?php };} ?>
    </ul>
    
</div>