<?php
use Zend\Session\Container;

$ssSystem = new Container('system');
$helperString = new \Ocoder\Helper\String;
?>

<!-- Main Content of Website -->
<div class="main-wrapper news-page">
    <!-- Main Content -->
    <div class="row main-content-wrapper">
        <!-- Main Content -->
        <div class="main-content col-sm-8">
            <img src="<?php echo URL_TEMPLATE . '/frontend/images/banner-sub.jpg' ?>" class="img-thumbnail banner-sub">

            <?php
            if ($ssSystem->language == DEFAULT_LANGUAGE) {
                $name = $this->item->name;
                $intro = $this->item->intro;
                $content = $this->item->content;
            } else {
                $nameLang = json_decode($this->item->name_lang);
                $nameField = 'name_' . $ssSystem->language;
                $name = $nameLang->$nameField;
                $introLang = json_decode($this->item->intro_lang);
                $introField = 'intro_' . $ssSystem->language;
                $intro = $introLang->$introField;
                $contentLang = json_decode($this->item->content_lang);
                $contentField = 'content_' . $ssSystem->language;
                $content = $contentLang->$contentField;
            }
            ?>

            <!-- Category List -->
            <div class="row categories">
                <h3 class="col-sm-12 header-title"><span class="glyphicon glyphicon-th-large" aria-hidden="true"></span> <?php echo $name ?></h3>
                <div class="col-sm-12"><strong><?php echo $intro; ?></strong></div>
                <div class="col-sm-12"><?php echo $content; ?></div>
            </div><!-- END Category Product List -->
        </div>

        <!-- Sidebar right -->
        <div class="sidebar-right col-sm-4">
            <?php            
            if ($this->item->category_id == SERVICE_CATEGORY_ID) {
                echo $this->blkServices();
                echo $this->blkProductCategory();
            }

            // Sidebar Right Main Job Block
            echo $this->blkNewsCategory();
            // Sidebar Right Video Block
            echo $this->blkVideo();
            // Sidebar Right Featured News
            echo $this->blkLatestNews();
            ?>
        </div><!-- Sidebar Right -->
    </div><!-- End Main Content -->