<?php
$urlCSS_DSDN = URL_TEMPLATE . '/frontend_dsdn/css';
$urlJS_DSDN = URL_TEMPLATE . '/frontend_dsdn/js';
$urlImage_DSDN = URL_TEMPLATE . '/frontend_dsdn/img';

use Zend\Session\Container;

$ssSystem = new Container('system');
$helperString = new \Ocoder\Helper\String;

?>
<?php
            if ($ssSystem->language == DEFAULT_LANGUAGE) {
                $name = $this->item->name;
                $intro = $this->item->intro;
                $content = $this->item->content;
            } else {
                $nameLang = json_decode($this->item->name_lang);
                $nameField = 'name_' . $ssSystem->language;
                $name = $nameLang->$nameField;
                $introLang = json_decode($this->item->intro_lang);
                $introField = 'intro_' . $ssSystem->language;
                $intro = $introLang->$introField;
                $contentLang = json_decode($this->item->content_lang);
                $contentField = 'content_' . $ssSystem->language;
                $content = $contentLang->$contentField;
            }
            ?>
    <div class="row">
        <div class="container contact-content" style="padding: 0">
            <img src="<?php echo $urlImage_DSDN?>/news.jpg" alt="">   
            <p class="contact_p">Tin tức</p>
        </div>

    </div>
    <div class="row page-default ">
        <div class="container content">
            <div class="breakum-line">
                <a href="<?php echo URL_APPLICATION ?>"><?php echo HOME ?></a>/<span> <?php echo $name ?></span>
            </div>
        
            <div class="col-md-8 block">
                <div class="news_content">

                    <p class="new_tittle block"><?php echo $name?></p>
                    
                    <div class="short_des block"><?php echo $intro; ?></div>
                    <?php echo $content; ?>
                </div>
            </div>
            <div class="col-md-4 pull-right">
                <div class="search padding_right5 block">
                    <form action="<?php echo URL_APPLICATION . '/tim-kiem/' ?>" method="GET">
                        <input type="text" class="form-control input-search" id="keyword-search" maxlength="64" name='tk' placeholder="<?php echo SEARCH ?>" value="<?php echo array_key_exists('tk', $_GET) ? $_GET['tk'] : '' ?>" />
                        <button type="submit" class="btn btn-primary btn-search"><i class="fa fa-search"></i><p><?php echo SEARCH ?></p></button>
                    </form>
                </div> 
                <div class="block">
                
                <?php $this->blkLatestNews(); ?>
            
                </div>

                <div class="block">
                    <?php $this->blkVideo();?>
                </div>
                
            </div>
            
        </div>
    </div> 