<?php
$urlCSS_DSDN = URL_TEMPLATE . '/frontend_dsdn/css';
$urlJS_DSDN = URL_TEMPLATE . '/frontend_dsdn/js';
$urlImage_DSDN = URL_TEMPLATE . '/frontend_dsdn/img';

use Zend\Session\Container;

$ssSystem = new Container('system');
$helperString = new \Ocoder\Helper\String;

$featuredProducts = $this->featuredProducts;
$arrayNews= array (NEWS_CATEGORY_ID,RELATENEWS_CATEGORY_ID,INTERNALNEWS_CATEGORY_ID,RECRUITMENT_CATEGORY_ID);
$arrayService= array (SERVICE_CATEGORY_ID);
$arrayShareholder= array(SHAREHOLDER_CATEGORY_ID ,NOTIFICATION_CATEGORY_ID,FINANCIAL_CATEGORY_ID,SHAREHOLDER_MEET_CATEGORY_ID,SHAREINFO_CATEGORY_ID,ANNUALREPORT_CATEGORY_ID,BOARDREPORT_CATEGORY_ID,GOVERNANCERULE_CATEGORY_ID,PROSPECTUSREPORT_CATEGORY_ID,CHARTERED_CATEGORY_ID );
$arrayAboutus =  array(COMPANY_INFO_CATEGORY_ID);
?>

<div class="row">
        <div class="container contact-content" style="padding: 0">
            <img src="<?php echo $urlImage_DSDN ?>/news.jpg" alt="">   
            <p class="contact_p">Tin Tức</p>
        </div>

    </div>
    <div class="row page-default ">
        <div class="container content">
            <div class="breakum-line">
                <a href="">Trang chủ</a>/<span> Tin tức </span>
            </div>
            <?php
                 $Parent_category=$this->categoryInfo->id;

                if ($ssSystem->language == DEFAULT_LANGUAGE) {
                    $name = $this->categoryInfo->name;
                } else {
                    $nameLang = json_decode($this->categoryInfo->name_lang);
                    $nameField = 'name_' . $ssSystem->language;
                    $name = $nameLang->$nameField;
                }
                ?>
            <div class="col-md-4 pull-left">
               <?php if(in_array($Parent_category,$arrayNews)){
                echo "1";
                    $this->blkNewsList();
                }
                if(in_array($Parent_category,$arrayService)){
                     echo "2";
                    $this->blkServicCateList();
                }
                if(in_array($Parent_category,$arrayShareholder)){
                     echo "3";
                    $this->blkShareHolList();
                }
                if(in_array($Parent_category,$arrayAboutus)){
                     echo "4";
                    $this->blkAboutUs();
                }
            ?>
            </div>
            <div class="col-md-8 block">
                <div class="news">
                    <span class="new_tittle"><?php echo $name ;?></span>
                    <hr>
                    <?php
                foreach ($this->articles as $article) {
                    if ($ssSystem->language == DEFAULT_LANGUAGE) {
                        $name = $article->name;
                        $alias = $article->alias;
                        $intro = $article->intro;
                    } else {
                        $nameLang = json_decode($article->name_lang);
                        $nameField = 'name_' . $ssSystem->language;
                        $name = $nameLang->$nameField;
                        $aliasLang = json_decode($article->alias_lang);
                        $aliasField = 'alias_' . $ssSystem->language;
                        $alias = $aliasLang->$aliasField;
                        $introLang = json_decode($article->intro_lang);
                        $introField = 'intro_' . $ssSystem->language;
                        $intro = $introLang->$introField;
                    }

                    if (trim($article->thumbnail) && $helperString->isUrlExist(URL_APPLICATION . $article->thumbnail)) {
                        $imageUrl = URL_APPLICATION . $article->thumbnail;
                    } else {
                        $imageUrl = $urlImage_DSDN . '/tinanh/no-image.png';
                    }
                    ?>
                    <div class="new_box">
                        <div class="first_news">
                           <img src="<?php echo $imageUrl ?>" alt="thumbnail" class="first_thumb"/>
                            <div class="first_new_content">
                                <a href="<?php echo URL_APPLICATION . '/bv/' . $alias ?>" class="links_tittle"><?php echo $name ;?></a>
                                <span>Thứ 4, 01/06/2016 , 9:37:03</span>
                                <p><?php echo $helperString->summary($intro, 250, true, true); ?></p>
                                <a href="<?php echo URL_APPLICATION . '/bv/' . $alias ?>" class="link_detail"> Xem chi tiết</a>
                            </div> 
                        </div>
                        <hr class="block">
                    </div>
                     <?php } //end foreach ?>
                    <!--<div class="new_box">
                        <div class="first_news">
                          <img src="<?php echo $urlImage_DSDN ?>/tinanh/new1.jpg" alt="thumbnail" class="first_thumb"/>
                            <div class="first_new_content">
                                <a href="news_detail.php" class="links_tittle">Di dời ga Đà Nẵng tốn gần 10.000 tỉ đồngs</a>
                                <span>Thứ 4, 01/06/2016 , 9:37:03</span>
                                <p>Ngày 15-3, đại diện tư vấn của Ngân hàng thế giới (WB) có buổi làm việc với UBND TP Đà Nẵng về Dự án di dời ga đường sắt Đà Nẵng và tái phát triển đô thị...</p>
                                <a href="news_detail.php" class="link_detail"> Xem chi tiết</a>
                            </div> 
                        </div>
                        <hr class="block">
                    </div>
                    <div class="new_box">
                        <div class="first_news">
                          <img src="<?php echo $urlImage_DSDN ?>/tinanh/new1.jpg" alt="thumbnail" class="first_thumb"/>
                            <div class="first_new_content">
                                <a href="news_detail.php" class="links_tittle">Di dời ga Đà Nẵng tốn gần 10.000 tỉ đồngs</a>
                                <span>Thứ 4, 01/06/2016 , 9:37:03</span>
                                <p>Ngày 15-3, đại diện tư vấn của Ngân hàng thế giới (WB) có buổi làm việc với UBND TP Đà Nẵng về Dự án di dời ga đường sắt Đà Nẵng và tái phát triển đô thị...</p>
                                <a href="news_detail.php" class="link_detail"> Xem chi tiết</a>
                            </div> 
                        </div>
                        <hr class="block">
                    </div>
                    <div class="new_box">
                        <div class="first_news">
                           <img src="<?php echo $urlImage_DSDN ?>/tinanh/new1.jpg" alt="thumbnail" class="first_thumb"/>
                            <div class="first_new_content">
                                <a href="news_detail.php" class="links_tittle">Di dời ga Đà Nẵng tốn gần 10.000 tỉ đồngs</a>
                                <span>Thứ 4, 01/06/2016 , 9:37:03</span>
                                <p>Ngày 15-3, đại diện tư vấn của Ngân hàng thế giới (WB) có buổi làm việc với UBND TP Đà Nẵng về Dự án di dời ga đường sắt Đà Nẵng và tái phát triển đô thị...</p>
                                <a href="news_detail.php" class="link_detail"> Xem chi tiết</a>
                            </div> 
                        </div>
                        <hr class="block">
                    </div>
                    <div class="new_box">
                        <div class="first_news">
                           <img src="<?php echo $urlImage_DSDN ?>/tinanh/new1.jpg" alt="thumbnail" class="first_thumb"/>
                            <div class="first_new_content">
                                <a href="news_detail.php" class="links_tittle">Di dời ga Đà Nẵng tốn gần 10.000 tỉ đồngs</a>
                                <span>Thứ 4, 01/06/2016 , 9:37:03</span>
                                <p>Ngày 15-3, đại diện tư vấn của Ngân hàng thế giới (WB) có buổi làm việc với UBND TP Đà Nẵng về Dự án di dời ga đường sắt Đà Nẵng và tái phát triển đô thị...</p>
                                <a href="news_detail.php" class="link_detail"> Xem chi tiết</a>
                            </div> 
                        </div>
                        <hr class="block">
                    </div>
                    <div class="new_box">
                        <div class="first_news">
                           <img src="<?php echo $urlImage_DSDN ?>/tinanh/new1.jpg" alt="thumbnail" class="first_thumb"/>
                            <div class="first_new_content">
                                <a href="" class="links_tittle">Di dời ga Đà Nẵng tốn gần 10.000 tỉ đồngs</a>
                                <span>Thứ 4, 01/06/2016 , 9:37:03</span>
                                <p>Ngày 15-3, đại diện tư vấn của Ngân hàng thế giới (WB) có buổi làm việc với UBND TP Đà Nẵng về Dự án di dời ga đường sắt Đà Nẵng và tái phát triển đô thị...</p>
                                <a href="" class="link_detail"> Xem chi tiết</a>
                            </div> 
                        </div>
                        <hr class="block">
                    </div>
                    <div class="new_box">
                        <div class="first_news">
                           <img src="<?php echo $urlImage_DSDN ?>/tinanh/new1.jpg" alt="thumbnail" class="first_thumb"/>
                            <div class="first_new_content">
                                <a href="" class="links_tittle">Di dời ga Đà Nẵng tốn gần 10.000 tỉ đồngs</a>
                                <span>Thứ 4, 01/06/2016 , 9:37:03</span>
                                <p>Ngày 15-3, đại diện tư vấn của Ngân hàng thế giới (WB) có buổi làm việc với UBND TP Đà Nẵng về Dự án di dời ga đường sắt Đà Nẵng và tái phát triển đô thị...</p>
                                <a href="" class="link_detail"> Xem chi tiết</a>
                            </div> 
                        </div>
                        <hr class="block">
                    </div>-->
                    <!-- PAGINATION -->
                    <?php
                        $aliasCategory = array(
                            COMPANY_INFO_CATEGORY_ID => '/' . URL_ALIAS_INTRO,
                            SERVICE_CATEGORY_ID => '/' . URL_ALIAS_SERVICE,
                            RECRUITMENT_CATEGORY_ID => '/' . URL_ALIAS_RECRUITMENT,
                            NEWS_CATEGORY_ID => '/' . URL_ALIAS_NEWS,
                            SHAREHOLDER_CATEGORY_ID => '/' . URL_ALIAS_SHAREHOLDER,
                        );
                        if ($ssSystem->language == DEFAULT_LANGUAGE) {
                            $alias = $this->categoryInfo->alias;
                        } else {
                            $langObj = json_decode($this->categoryInfo->alias_lang);
                            $aliasField = 'alias_' . $ssSystem->language;
                            $alias = $langObj->$aliasField;
                        }
                        
                        $currentURL = URL_APPLICATION . $aliasCategory[$this->categoryInfo->parent_id] . '/' . $alias;
                        
                        echo $this->paginationControl($this->paginator, 'sliding', 'paginator.phtml', array('currentURL' => $currentURL));
                        ?>
                    
                </div>
            </div>
            
        </div>
    </div> 