<?php
$urlCSS_DSDN = URL_TEMPLATE . '/frontend_dsdn/css';
$urlJS_DSDN = URL_TEMPLATE . '/frontend_dsdn/js';
$urlImage_DSDN = URL_TEMPLATE . '/frontend_dsdn/img';

use Zend\Session\Container;

$ssSystem = new Container('system');
$helperString = new \Ocoder\Helper\String;
$arrayNews= array (NEWS_CATEGORY_ID,RELATENEWS_CATEGORY_ID,INTERNALNEWS_CATEGORY_ID,RECRUITMENT_CATEGORY_ID);
$arrayService= array (SERVICE_CATEGORY_ID);
$arrayShareholder= array(SHAREHOLDER_CATEGORY_ID ,NOTIFICATION_CATEGORY_ID,FINANCIAL_CATEGORY_ID,SHAREHOLDER_MEET_CATEGORY_ID,SHAREINFO_CATEGORY_ID,ANNUALREPORT_CATEGORY_ID,BOARDREPORT_CATEGORY_ID,GOVERNANCERULE_CATEGORY_ID,PROSPECTUSREPORT_CATEGORY_ID,CHARTERED_CATEGORY_ID );
$arrayAboutus =  array(COMPANY_INFO_CATEGORY_ID);
echo "detail";

?>

<div class="row">
    <div class="container contact-content" style="padding: 0">
        <img src="<?php echo $urlImage_DSDN ?>/service.jpg" alt="">   
        <p class="contact_p">Dịch vụ</p>
    </div>

</div>
<?php
     $Parent_category=$this->categoryInfo->id;
    if ($ssSystem->language == DEFAULT_LANGUAGE) {
        $name = $this->categoryInfo->name;
    } else {
        $nameLang = json_decode($this->categoryInfo->name_lang);
        $nameField = 'name_' . $ssSystem->language;
        $name = $nameLang->$nameField;
    }
    ?>
<div class="row page-default ">
    <div class="container content">
        <div class="breakum-line">
            <a href="">Trang chủ</a>/<span> <?php echo $name ?></span>
        </div>
        <div class="col-md-4 block ">
            <!--<div class="search padding_right5 block">
                <form action="<?php //echo URL_APPLICATION . '/tim-kiem/' ?>" method="GET">
                    <input type="text" class="form-control input-search" id="keyword-search" maxlength="64" name='tk' placeholder="<?php //echo SEARCH ?>" value="<?php //echo array_key_exists('tk', $_GET) ? $_GET['tk'] : '' ?>" />
                    <button type="submit" class="btn btn-primary btn-search"><i class="fa fa-search"></i><p><?php //echo SEARCH ?></p></button>
                </form>
            </div>
            
       
            
            <div class=" block">
                <?php //$this->blkLatestNews(); ?>
            </div>
            <div class="block">
                <?php //$this->blkVideo();?>
            </div>--> 
            <?php if(in_array($Parent_category,$arrayNews)){
                    $this->blkNewsList();
                }
                if(in_array($Parent_category,$arrayService)){
                    $this->blkServicCateList();
                }
                if(in_array($Parent_category,$arrayShareholder)){
                    $this->blkShareHolList();
                }
                if(in_array($Parent_category,$arrayAboutus)){
                    $this->blkAboutUs();
                }
            ?>
        </div>
        <div class="col-md-8 block">
        <?php
        foreach ($this->articles as $article) {
                    if ($ssSystem->language == DEFAULT_LANGUAGE) {
                       
                        $name = $article->name;
                        $intro = $article->intro;
                        $alias = $article->alias;
                    } else {
                        $nameLang = json_decode($article->name_lang);
                        $nameField = 'name_' . $ssSystem->language;
                        $name = $nameLang->$nameField;
                        $introLang = json_decode($article->intro_lang);
                        $introField = 'intro_' . $ssSystem->language;
                        $intro = $introLang->$introField;
                        $aliasLang = json_decode($article->alias_lang);
                        $aliasField = 'alias_' . $ssSystem->language;
                        $alias = $aliasLang->$aliasField;
                    }

                    if (trim($article->thumbnail) && $helperString->isUrlExist(URL_APPLICATION . $article->thumbnail)) {
                        $imageUrl = URL_APPLICATION . $article->thumbnail;
                    } else {
                        $imageUrl = $urlImage_DSDN . '/tinanh/no-image.png';
                    }
                    ?>
            <div class="news">
                <div class="new_box">
                    <div class="first_news">
                        <a href="<?php echo URL_APPLICATION . '/bv/' . $alias ?>"><img src="<?php echo $imageUrl ?>" alt="<?php echo $name ?>" class="first_thumb"/></a>
                        <div class="first_new_content">
                            <a href="<?php echo URL_APPLICATION . '/bv/' . $alias ?>" class="links_tittle"><?php echo $name; ?></a>
                            <hr class="block">
                            <p><?php echo $helperString->summary($intro, 250, true, true); ?></p>
                            
                        </div> 
                    </div>
                </div>
            </div>
             <hr class="block">
            <?php } ?>
                
        </div>

         

            
        
            
    </div>
</div> 