<?php
$urlCSS_DSDN = URL_TEMPLATE . '/frontend_dsdn/css';
$urlJS_DSDN = URL_TEMPLATE . '/frontend_dsdn/js';
$urlImage_DSDN = URL_TEMPLATE . '/frontend_dsdn/img';

use Zend\Session\Container;

$ssSystem = new Container('system');
$helperString = new \Ocoder\Helper\String;

?>

<div class="row">
    <div class="container contact-content" style="padding: 0">
        <img src="<?php echo $urlImage_DSDN?>/news.jpg" alt="">   
        <p class="contact_p">Tin Tức</p>
    </div>

</div>
<div class="row page-default ">
    <div class="container content">
        <div class="breakum-line">
            <a href="<?php echo URL_APPLICATION?>"><?php echo HOME?></a>/<span> Tin tức </span>
        </div>
        
        <div class="col-md-8 block">
        <?php 
            foreach ($this->categoryNews as $category) { 
                if ($ssSystem->language == DEFAULT_LANGUAGE) {
                    $name = $category->name;
                    $alias = $category->alias;
                    $intro = $category->intro;
                } else {
                    $nameLang = json_decode($category->name_lang);
                    $nameField = 'name_' . $ssSystem->language;
                    $name = $nameLang->$nameField;
                    $aliasLang = json_decode($category->alias_lang);
                    $aliasField = 'alias_' . $ssSystem->language;
                    $alias = $aliasLang->$aliasField;
                    $introLang = json_decode($category->intro_lang);
                    $introField = 'intro_' . $ssSystem->language;
                    $intro = $introLang->$introField;
                }
            ?>
            <div class="news block">
                <a href="<?php echo URL_APPLICATION . '/' . URL_ALIAS_NEWS . '/' . $alias ?>"><span class="new_tittle"><?php echo $helperString->summary($name, 50, true, true); ?></span></a>
                <hr>
                <div class="new_box">
                <?php 
                    $count = 1;
                    foreach ($category->articles as $article) { 
                        if ($ssSystem->language == DEFAULT_LANGUAGE) {
                            $name = $article->name;
                            $alias = $article->alias;
                            $intro = $article->intro;
                        } else {
                            $nameLang = json_decode($article->name_lang);
                            $nameField = 'name_' . $ssSystem->language;
                            $name = $nameLang->$nameField;
                            $aliasLang = json_decode($article->alias_lang);
                            $aliasField = 'alias_' . $ssSystem->language;
                            $alias = $aliasLang->$aliasField;
                            $introLang = json_decode($article->intro_lang);
                            $introField = 'intro_' . $ssSystem->language;
                            $intro = $introLang->$introField;
                        }
                        
                        if (trim($article->thumbnail) && $helperString->isUrlExist(URL_APPLICATION . $article->thumbnail)) {
                            $imageUrl = URL_APPLICATION . $article->thumbnail;
                        } else {
                            $imageUrl = $urlImage_DSDN.'/tinanh/no-image.png';
                        }
                        
                        if($count > 1){
                            $count++;
                    ?>
                     <hr class="block">
                    <div class="under_new_content">
                        <a href="<?php echo URL_APPLICATION . '/bv/' . $alias ?>"> <?php echo $helperString->summary($name, 60, true, true); ?></a>
                    </div>
                    
                    <?php   
                        } else {
                            $count++;
                    ?>
                    <!-- start row block -->
                    <div class="first_news">
                        <a href="<?php echo URL_APPLICATION . '/bv/' . $alias ?>"><img src="<?php echo $imageUrl ?>" alt="thumbnail" class="first_thumb"/></a>
                        <div class="first_new_content">
                            <a href="<?php echo URL_APPLICATION . '/bv/' . $alias ?>" class="links_tittle"><?php echo $name?></a>
                            <span>Thứ 4, 01/06/2016 , 9:37:03</span>
                            <p><?php echo $intro ?></p>
                            <a href="<?php echo URL_APPLICATION . '/bv/' . $alias ?>" class="link_detail"> Xem chi tiết</a>
                        </div> 
                    </div>
                    <!-- end row block -->
                   
                    
                    
                </div>
                <?php       
                        }//end if
                    }//end foreach ?>    
            </div>
            <hr>
            <?php }//end foreach ?>
        </div>
        <div class="col-md-4 block">
            <div class="padding_right5">
                <div class="search block ">
                    <input type="text" class="form-control input-search" maxlength="64" placeholder="Tìm kiếm" />
                    <button type="submit" class="btn btn-primary btn-search"><i class="fa fa-search"></i><p>Tìm kiếm</p></button>
                </div> 
            </div> 
            <div class="tinanh block">
                <span class="tittle">Tin ảnh</span>
                <div class="items">
                <a href=""><img src="img/tinanh/tin anh 1_.jpg" alt="thumbnail" title="Hoạt động công ty" class="img"></a><a href="#" title="Hoạt động công ty" class="newslink">Đà Nẵng: Sẽ sớm di dời ga đường sắt ra khỏi nội thành</a><br>
                <span class="info">32 photos | 26639 view</span>
                </div>
                <div class="items">
                <a href=""><img src="img/tinanh/tin anh 2_.jpg" alt="thumbnail" title="Hoạt động công ty" class="img"></a><a href="#" title="Hoạt động công ty" class="newslink">Triển lãm công nghệ khai khoáng</a><br>
                <span class="info">32 photos | 26639 view</span>
                </div>
                <div class="items">
                <a href=""><img src="img/tinanh/tin anh 3_.jpg" alt="thumbnail" title="Hoạt động công ty" class="img"></a>
                <a href="#" title="Hoạt động công ty" class="newslink">Ga đường sắt mới sẽ được đặt tại quận Liên Chiểu</a>
                <span class="info">32 photos | 26639 view</span>
                </div>
                <div class="items">
                <a href=""><img src="img/tinanh/post1.jpg" alt="thumbnail" title="Hoạt động công ty" class="img"></a><a href="#" title="Hoạt động công ty" class="newslink">Phương án di dời và xây dựng ga đường sắt Đà Nẵng</a><br>
                <span class="info">32 photos | 26639 view</span>
                </div>
                <div class="items">
                <a href=""><img src="img/tinanh/tin anh 2_.jpg" alt="thumbnail" title="Hoạt động công ty" class="img"></a><a href="#" title="Hoạt động công ty" class="newslink">Triển lãm công nghệ khai khoáng</a><br>
                <span class="info">32 photos | 26639 view</span>
                </div>

                <div class="link"><a href="" class="linkmore">Xem thêm </a></div>
            </div>
            <div class="otherlink block">
                <span>video</span>
                <iframe width="100%" height="315" src="https://www.youtube.com/embed/ahLjVibR6oY" frameborder="0" allowfullscreen></iframe>
            </div>
            <div class="tinanh block">
                <span class="tittle">Tin Thể thao</span>
                <div class="items">
                <a href=""><img src="img/tinanh/tin anh 1_.jpg" alt="thumbnail" title="Hoạt động công ty" class="img"></a><a href="#" title="Hoạt động công ty" class="newslink">Đà Nẵng: Sẽ sớm di dời ga đường sắt ra khỏi nội thành</a><br>
                <span class="info">32 photos | 26639 view</span>
                </div>
                <div class="items">
                <a href=""><img src="img/tinanh/tin anh 2_.jpg" alt="thumbnail" title="Hoạt động công ty" class="img"></a><a href="#" title="Hoạt động công ty" class="newslink">Triển lãm công nghệ khai khoáng</a><br>
                <span class="info">32 photos | 26639 view</span>
                </div>
                <div class="items">
                <a href=""><img src="img/tinanh/tin anh 3_.jpg" alt="thumbnail" title="Hoạt động công ty" class="img"></a>
                <a href="#" title="Hoạt động công ty" class="newslink">Ga đường sắt mới sẽ được đặt tại quận Liên Chiểu</a>
                <span class="info">32 photos | 26639 view</span>
                </div>
                <div class="items">
                <a href=""><img src="img/tinanh/post1.jpg" alt="thumbnail" title="Hoạt động công ty" class="img"></a><a href="#" title="Hoạt động công ty" class="newslink">Phương án di dời và xây dựng ga đường sắt Đà Nẵng</a><br>
                <span class="info">32 photos | 26639 view</span>
                </div>
                <div class="items">
                <a href=""><img src="img/tinanh/tin anh 2_.jpg" alt="thumbnail" title="Hoạt động công ty" class="img"></a><a href="#" title="Hoạt động công ty" class="newslink">Triển lãm công nghệ khai khoáng</a><br>
                <span class="info">32 photos | 26639 view</span>
                </div>
                <div class="link"><a href="" class="linkmore">Xem thêm </a></div>
            </div>
        </div>

        
        
    </div>
</div> 