<?php
$urlCSS_DSDN = URL_TEMPLATE . '/frontend_dsdn/css';
$urlJS_DSDN = URL_TEMPLATE . '/frontend_dsdn/js';
$urlImage_DSDN = URL_TEMPLATE . '/frontend_dsdn/img';

use Zend\Session\Container;

$ssSystem = new Container('system');
$helperString = new \Ocoder\Helper\String;



echo "index";
?>
<?php
echo "<pre>";
var_dump($categoryNews);
echo "</pre>";
     //$Parent_category=$this->categoryInfo->id;
    if ($ssSystem->language == DEFAULT_LANGUAGE) {
        $name = $this->categoryInfo->name;
    } else {
        $nameLang = json_decode($this->categoryInfo->name_lang);
        $nameField = 'name_' . $ssSystem->language;
        $name = $nameLang->$nameField;
    }
    ?>
<div class="row">
    <div class="container contact-content" style="padding: 0">
        <img src="<?php echo $urlImage_DSDN?>/news.jpg" alt="">   
        <p class="contact_p">Tin Tức</p>
    </div>

</div>
<div class="row page-default ">
    <div class="container content">
        <div class="breakum-line">
            <a href="<?php echo URL_APPLICATION?>"><?php echo HOME?></a>/<span><?php echo $name?></span>
        </div>
        
        <div class="col-md-8 block">
        <?php 
            foreach ($this->categoryNews as $category) { 
                if ($ssSystem->language == DEFAULT_LANGUAGE) {
                    $name = $category->name;
                    $alias = $category->alias;
                    $intro = $category->intro;
                } else {
                    $nameLang = json_decode($category->name_lang);
                    $nameField = 'name_' . $ssSystem->language;
                    $name = $nameLang->$nameField;
                    $aliasLang = json_decode($category->alias_lang);
                    $aliasField = 'alias_' . $ssSystem->language;
                    $alias = $aliasLang->$aliasField;
                    $introLang = json_decode($category->intro_lang);
                    $introField = 'intro_' . $ssSystem->language;
                    $intro = $introLang->$introField;
                }
            ?>
            <div class="news block">
                <a href="<?php echo URL_APPLICATION . '/' . URL_ALIAS_NEWS . '/' . $alias ?>"><span class="new_tittle"><?php echo $helperString->summary($name, 50, true, true); ?></span></a>
                <hr>
                <div class="new_box">
                <?php 
                    $count = 1;
                    foreach ($category->articles as $article) { 
                        if ($ssSystem->language == DEFAULT_LANGUAGE) {
                            $name = $article->name;
                            $alias = $article->alias;
                            $intro = $article->intro;
                        } else {
                            $nameLang = json_decode($article->name_lang);
                            $nameField = 'name_' . $ssSystem->language;
                            $name = $nameLang->$nameField;
                            $aliasLang = json_decode($article->alias_lang);
                            $aliasField = 'alias_' . $ssSystem->language;
                            $alias = $aliasLang->$aliasField;
                            $introLang = json_decode($article->intro_lang);
                            $introField = 'intro_' . $ssSystem->language;
                            $intro = $introLang->$introField;
                        }
                        
                        if (trim($article->thumbnail) && $helperString->isUrlExist(URL_APPLICATION . $article->thumbnail)) {
                            $imageUrl = URL_APPLICATION . $article->thumbnail;
                        } else {
                            $imageUrl = $urlImage_DSDN.'/tinanh/no-image.png';
                        }
                        
                        if($count > 1){
                            $count++;
                    ?>
                    <hr class="block">
                    <div class="under_new_content">
                        <a href="<?php echo URL_APPLICATION . '/bv/' . $alias ?>"> <?php echo $helperString->summary($name, 60, true, true); ?></a>
                    </div>
                    
                    <?php   
                        } else {
                            $count++;
                    ?>
                    <!-- start row block -->
                    <div class="first_news">
                        <a href="<?php echo URL_APPLICATION . '/bv/' . $alias ?>"><img src="<?php echo $imageUrl ?>" alt="thumbnail" class="first_thumb"/></a>
                        <div class="first_new_content">
                            <a href="<?php echo URL_APPLICATION . '/bv/' . $alias ?>" class="links_tittle"><?php echo $name?></a>
                            <span>Thứ 4, 01/06/2016 , 9:37:03</span>
                            <p><?php echo $intro ?></p>
                            <a href="<?php echo URL_APPLICATION . '/bv/' . $alias ?>" class="link_detail"> Xem chi tiết</a>
                        </div> 
                    </div>
                    <!-- end row block -->
                    <?php       
                        }//end if
                    }//end foreach ?>   
                    
                    
                </div>
                
            </div>
            <hr>
            <?php }//end foreach ?>
        </div>
        <div class="col-md-4 block">
            <div class="search padding_right5 block">
                <form action="<?php echo URL_APPLICATION . '/tim-kiem/' ?>" method="GET">
                    <input type="text" class="form-control input-search" id="keyword-search" maxlength="64" name='tk' placeholder="<?php echo SEARCH ?>" value="<?php echo array_key_exists('tk', $_GET) ? $_GET['tk'] : '' ?>" />
                    <button type="submit" class="btn btn-primary btn-search"><i class="fa fa-search"></i><p><?php echo SEARCH ?></p></button>
                </form>
            </div> 
            
            <div class="block">
                <?php $this->blkVideo();?>
            </div>
            <div class=" block">
                <?php $this->blkLatestNews(); ?>
            </div>
        </div>
    </div>
</div> 