<?php
$urlCSS = URL_TEMPLATE . '/backend/css';
$urlJS = URL_TEMPLATE . '/backend/js';
$urlImage = URL_TEMPLATE . '/backend/img';
?>

<!DOCTYPE html>
<html style="background-color: #222222 !important;">
    <head><?php
        echo $this->headTitle()->prepend(PAGE_TITLE);
        echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendName('description', PAGE_TITLE)
                ->setCharset('utf-8');

        echo $this->headLink()->appendStylesheet(array(
                    'rel' => 'shortcut icon',
                    'type' => 'image/x-icon',
                    'href' => $urlImage . '/favicon.ico'
                        ), 'PREPEND')
                ->appendStylesheet($urlCSS . '/bootstrap.min.css')
                ->appendStylesheet($urlCSS . '/font-awesome.min.css')
                ->appendStylesheet($urlCSS . '/AdminLTE.css')
                ->appendStylesheet(URL_PUBLIC . '/plugins/bootstrapvalidation/dist/css/formValidation.css')
        ;
        echo $this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js')
                ->appendFile($urlJS . '/plugins/bootstrap.min.js')
                ->appendFile(URL_PUBLIC . '/plugins/bootstrapvalidation/dist/js/formValidation.js')
                ->appendFile(URL_PUBLIC . '/plugins/bootstrapvalidation/dist/js/framework/bootstrap.js')
        ;
        ?>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="bg-black">
        <?php echo $this->content; ?>
    </body>
</html>