<?php
$urlCSS = URL_TEMPLATE . '/backend/css';
$urlJS = URL_TEMPLATE . '/backend/js';
$urlImage = URL_TEMPLATE . '/backend/img';

?>

<!DOCTYPE html>
<html>
    <head><?php
        echo $this->headTitle()->prepend(PAGE_TITLE);
        echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendName('description', PAGE_TITLE)
                ->setCharset('utf-8');

        echo $this->headLink()->appendStylesheet(array(
                    'rel' => 'shortcut icon',
                    'type' => 'image/x-icon',
                    'href' => $urlImage . '/favicon.ico'
                        ), 'PREPEND')
                ->appendStylesheet($urlCSS . '/bootstrap.min.css')
                ->appendStylesheet(URL_PUBLIC . '/plugins/bootstrapvalidation/dist/css/formValidation.css')
                ->appendStylesheet($urlCSS . '/font-awesome.min.css')
                ->appendStylesheet($urlCSS . '/ionicons.min.css')
                ->appendStylesheet($urlCSS . '/AdminLTE.css')
                ->appendStylesheet($urlCSS . '/datatables/dataTables.bootstrap.css')
        ;
        echo $this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js')
//            $this->headScript()->appendFile('//code.jquery.com/jquery-1.11.2.min.js')
                ->appendFile($urlJS . '/plugins/bootstrap.min.js')
                ->appendFile($urlJS . '/AdminLTE/app.js')
                ->appendFile($urlJS . '/custom.js')
                ->appendFile(URL_PUBLIC . '/plugins/bootstrapvalidation/dist/js/formValidation.js')
                ->appendFile(URL_PUBLIC . '/plugins/bootstrapvalidation/dist/js/framework/bootstrap.js')
//                ->appendFile($urlJS . '/jquery.autocomplete.js')
                ->appendFile(URL_PUBLIC . '/plugins/ckeditor/ckeditor.js')
                ->appendFile(URL_PUBLIC . '/plugins/ckfinder/ckfinder.js')
        ;
        ?>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="skin-blue">
        <!-- header logo: style can be found in header.less -->
        <header class="header">
            <a href="<?php echo URL_APPLICATION . '/admin' ?>" class="logo"><?php echo PAGE_TITLE ?></a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-right">
                    <ul class="nav navbar-nav">
                        <?php echo $this->blkTopUserInfo(); ?>
                    </ul>
                </div>
            </nav>
        </header>
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="left-side sidebar-offcanvas">                
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">
                    <!-- Sidebar user panel -->
                    <?php echo $this->blkLeftUserInfo(); ?>
                    <!-- search form -->
                    <!--<form action="#" method="get" class="sidebar-form">
                        <div class="input-group">
                            <input type="text" name="q" class="form-control" placeholder="Search..."/>
                            <span class="input-group-btn">
                                <button type='submit' name='seach' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    </form>-->
                    <!-- /.search form -->
                    <!-- sidebar menu: : style can be found in sidebar.less -->
                    <ul class="sidebar-menu">
                        <li class="active">
                            <a href="<?php echo URL_APPLICATION . '/admin' ?>">
                                <i class="fa fa-dashboard"></i> <span><?php echo CONFIGS ?></span>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo URL_APPLICATION . '/admin/user' ?>">
                                <i class="glyphicon glyphicon-user"></i> <span><?php echo ADMINISTRATOR ?></span>
                            </a>
                        </li>
                        <!--<li>
                            <a href="<?php echo URL_APPLICATION . '/admin/productcategory' ?>">
                                <i class="fa fa-th"></i> <span><?php echo PRODUCT_CATEGORY ?></span>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo URL_APPLICATION . '/admin/product' ?>">
                                <i class="fa fa-th fa-camera"></i> <span><?php echo PRODUCT ?></span>
                            </a>
                        </li>-->
                        <li>
                            <a href="<?php echo URL_APPLICATION . '/admin/category/detail/' . SERVICE_CATEGORY_ID ?>">
                                <i class="fa fa-th fa-cloud"></i> <span><?php echo SERVICES ?></span>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo URL_APPLICATION . '/admin/category/detail/' . CAREER_CATEGORY_ID ?>">
                                <i class="fa fa-th fa-flag"></i> <span><?php echo CAREERS ?></span>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo URL_APPLICATION . '/admin/category/detail/' . COMPANY_INFO_CATEGORY_ID ?>">
                                <i class="fa fa-th fa-bar-chart-o"></i> <span><?php echo COMPANY_INFO ?></span>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo URL_APPLICATION . '/admin/category/child/' . NEWS_CATEGORY_ID ?>">
                                <i class="fa fa-th fa-coffee"></i> <span><?php echo NEWS ?></span>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo URL_APPLICATION . '/admin/category/child/' . SHAREHOLDER_CATEGORY_ID ?>">
                                <i class="fa fa-th fa-globe"></i> <span><?php echo SHAREHOLDER ?></span>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo URL_APPLICATION . '/admin/partner/' ?>">
                                <i class="glyphicon glyphicon-hand-right"></i> <span><?php echo PARTNER_MANAGEMENT ?></span>
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo URL_APPLICATION . '/admin/banner/' ?>">
                                <i class="glyphicon glyphicon-expand"></i> <span><?php echo BANNER_MANAGEMENT ?></span>
                            </a>
                        </li>
                        <!--
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-bar-chart-o"></i>
                                <span>Charts</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="pages/charts/morris.html"><i class="fa fa-angle-double-right"></i> Morris</a></li>
                                <li><a href="pages/charts/flot.html"><i class="fa fa-angle-double-right"></i> Flot</a></li>
                                <li><a href="pages/charts/inline.html"><i class="fa fa-angle-double-right"></i> Inline charts</a></li>
                            </ul>
                        </li>
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-laptop"></i>
                                <span>UI Elements</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="pages/UI/general.html"><i class="fa fa-angle-double-right"></i> General</a></li>
                                <li><a href="pages/UI/icons.html"><i class="fa fa-angle-double-right"></i> Icons</a></li>
                                <li><a href="pages/UI/buttons.html"><i class="fa fa-angle-double-right"></i> Buttons</a></li>
                                <li><a href="pages/UI/sliders.html"><i class="fa fa-angle-double-right"></i> Sliders</a></li>
                                <li><a href="pages/UI/timeline.html"><i class="fa fa-angle-double-right"></i> Timeline</a></li>
                            </ul>
                        </li>
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-edit"></i> <span>Forms</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="pages/forms/general.html"><i class="fa fa-angle-double-right"></i> General Elements</a></li>
                                <li><a href="pages/forms/advanced.html"><i class="fa fa-angle-double-right"></i> Advanced Elements</a></li>
                                <li><a href="pages/forms/editors.html"><i class="fa fa-angle-double-right"></i> Editors</a></li>                                
                            </ul>
                        </li>
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-table"></i> <span>Tables</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="pages/tables/simple.html"><i class="fa fa-angle-double-right"></i> Simple tables</a></li>
                                <li><a href="pages/tables/data.html"><i class="fa fa-angle-double-right"></i> Data tables</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="pages/calendar.html">
                                <i class="fa fa-calendar"></i> <span>Calendar</span>
                                <small class="badge pull-right bg-red">3</small>
                            </a>
                        </li>
                        <li>
                            <a href="pages/mailbox.html">
                                <i class="fa fa-envelope"></i> <span>Mailbox</span>
                                <small class="badge pull-right bg-yellow">12</small>
                            </a>
                        </li>
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-folder"></i> <span>Examples</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="pages/examples/invoice.html"><i class="fa fa-angle-double-right"></i> Invoice</a></li>
                                <li><a href="pages/examples/login.html"><i class="fa fa-angle-double-right"></i> Login</a></li>
                                <li><a href="pages/examples/register.html"><i class="fa fa-angle-double-right"></i> Register</a></li>
                                <li><a href="pages/examples/lockscreen.html"><i class="fa fa-angle-double-right"></i> Lockscreen</a></li>
                                <li><a href="pages/examples/404.html"><i class="fa fa-angle-double-right"></i> 404 Error</a></li>
                                <li><a href="pages/examples/500.html"><i class="fa fa-angle-double-right"></i> 500 Error</a></li>                                
                                <li><a href="pages/examples/blank.html"><i class="fa fa-angle-double-right"></i> Blank Page</a></li>
                            </ul>
                        </li>-->
                    </ul>
                </section>
                <!-- /.sidebar -->
            </aside>

            <!-- Right side column. Contains the navbar and content of the page -->
            <aside class="right-side">                
                <?php echo $this->content; ?>
            </aside><!-- /.right-side -->
        </div><!-- ./wrapper -->


        

    </body>
</html>