<?php
$urlCSS_DSDN = URL_TEMPLATE . '/frontend_dsdn/css';
$urlJS_DSDN = URL_TEMPLATE . '/frontend_dsdn/js';
$urlImage_DSDN = URL_TEMPLATE . '/frontend_dsdn/img';

use Zend\Session\Container;

$ssSystem = new Container('system');
$helperString = new \Ocoder\Helper\String;

?>
 <div class="row">
        <div class="container contact-content" style="padding: 0">
            <img src="<?php echo $urlImage_DSDN?>/news.jpg" alt="">   
            <p class="contact_p">Tin Tức</p>
        </div>

    </div>
    <div class="row page-default ">
        <div class="container content">
            <div class="breakum-line">
                <a href="<?php echo URL_APPLICATION ?>"><?php echo HOME ?></a>/<span> Lịch sử phát triển</span>
            </div>
        
            <div class="col-md-8 block">
                <section id="cd-timeline" class="cd-container">
                    <div class="cd-timeline-block">
                        <div class="cd-timeline-img cd-picture">
                            
                        </div> <!-- cd-timeline-img -->

                        <div class="cd-timeline-content">
                            <h2>Chuyển đổi thành công ty CP TTTH Đường sắt Đà Nẵng</h2>
                            <p>Chuyển đổi Công ty TNHH MTV Thông tin tín hiệu Đường sắt Đà Nẵng thành Công ty cổ phần Thông tin tín hiệu Đường sắt Đà Nẵng</p>
                            <span class="cd-date">14/01/2016</span>
                        </div> <!-- cd-timeline-content -->
                    </div> <!-- cd-timeline-block -->
                    <div class="cd-timeline-block">
                        <div class="cd-timeline-img cd-movie">
                           
                        </div> <!-- cd-timeline-img -->

                        <div class="cd-timeline-content">
                            <h2>Nhận huân chương độc lập hạng nhì</h2>
                            <p>Công ty Thông tin tín hiệu Đường sắt Đà Nẵng vinh dự được Chủ tịch nước trao tặng huân chương độc lập hạng nhì</p>
                            <span class="cd-date">23/08/2013</span>
                        </div> <!-- cd-timeline-content -->
                    </div> <!-- cd-timeline-block -->
                    <div class="cd-timeline-block">
                        <div class="cd-timeline-img cd-picture">
                            
                        </div> <!-- cd-timeline-img -->

                        <div class="cd-timeline-content">
                            <h2>Chuyển đổi thành công ty TNHH MTV TTTH Đường sắt Đà Nẵng</h2>
                            <p>Chuyển đổi Công ty Thông tin tín hiệu Đường sắt Đà Nẵng thành Công ty TNHH MTV Thông tin tín hiệu Đường sắt Đà Nẵng</p>
                            <span class="cd-date">29/06/2010</span>
                        </div> <!-- cd-timeline-content -->
                    </div> <!-- cd-timeline-block -->
                    <div class="cd-timeline-block">
                        <div class="cd-timeline-img cd-movie">
                           
                        </div> <!-- cd-timeline-img -->

                        <div class="cd-timeline-content">
                            <h2>Nhận huân chương độc lập hạng ba</h2>
                            <p>Công ty Thông tin tín hiệu Đường sắt Đà Nẵng vinh dự được Chủ tịch nước trao tặng huân chương độc lập hạng ba</p>
                            <span class="cd-date">24/04/2008</span>
                        </div> <!-- cd-timeline-content -->
                    </div> <!-- cd-timeline-block -->
                    <div class="cd-timeline-block">
                        <div class="cd-timeline-img cd-movie">
                          
                        </div> <!-- cd-timeline-img -->

                        <div class="cd-timeline-content">
                            <h2>Nhận huân chương lao động hạng nhất</h2>
                            <p>Công ty Thông tin tín hiệu Đường sắt Đà Nẵng vinh dự được Chủ tịch nước trao tặng huân chương Lao Động hạng nhất</p>
                            <span class="cd-date">19/05/2003</span>
                        </div> <!-- cd-timeline-content -->
                    </div> <!-- cd-timeline-block -->
                    <div class="cd-timeline-block">
                        <div class="cd-timeline-img cd-picture">
                            
                        </div> <!-- cd-timeline-img -->

                        <div class="cd-timeline-content">
                            <h2>Đổi tên thành công ty TTTH Đường sắt Đà Nẵng</h2>
                            <p>Đổi tên Xí nghiệp Thông tin tín hiệu đường sắt Đà Nẵng thành công ty Thông tin tín hiệu đường sắt Đà Nẵng</p>
                            <span class="cd-date">20/03/2003</span>
                        </div> <!-- cd-timeline-content -->
                    </div> <!-- cd-timeline-block -->
                    <div class="cd-timeline-block">
                        <div class="cd-timeline-img cd-movie">
                            
                        </div> <!-- cd-timeline-img -->

                        <div class="cd-timeline-content">
                            <h2>Nhận huân chương lao động hạng nhì</h2>
                            <p>Xí nghiệp Thông tin tín hiệu Đường sắt Đà Nẵng vinh dự được Chủ tịch nước trao tặng huân chương Lao Động hạng nhì</p>
                            <span class="cd-date">1999</span>
                        </div> <!-- cd-timeline-content -->
                    </div> <!-- cd-timeline-block -->

                    <div class="cd-timeline-block">
                        <div class="cd-timeline-img cd-movie">
                            
                        </div> <!-- cd-timeline-img -->

                        <div class="cd-timeline-content">
                            <h2>Nhận huân chương lao động hạng ba</h2>
                            <p>Xí nghiệp Thông tin tín hiệu Đường sắt Đà Nẵng vinh dự được Chủ tịch nước trao tặng huân chương Lao Động hạng ba</p>
                            <span class="cd-date">1997</span>
                        </div> <!-- cd-timeline-content -->
                    </div> <!-- cd-timeline-block -->

                    <div class="cd-timeline-block">
                        <div class="cd-timeline-img cd-picture">
                            
                        </div> <!-- cd-timeline-img -->

                        <div class="cd-timeline-content">
                            <h2>Đổi tên thành XN TTTH Đường sắt Đà Nẵng</h2>
                            <p>Đổi tên Xí nghiệp Thông tin tín hiệu 3 thành Xí nghiệp Thông tin tín hiệu Đường sắt Đà Nẵng</p>
                            <span class="cd-date">25/11/1989</span>
                        </div> <!-- cd-timeline-content -->
                    </div> <!-- cd-timeline-block -->

                    <div class="cd-timeline-block">
                        <div class="cd-timeline-img cd-location">
                            
                        </div> <!-- cd-timeline-img -->

                        <div class="cd-timeline-content">
                            <h2>Đổi tên thành XN TTTH số 3</h2>
                            <p>Đổi tên đoạn Thông tin tín hiệu Đà Nẵng thành Xí nghiệp Thông tin tín hiệu 3 </p>
                            <span class="cd-date">30/11/1983</span>
                        </div> <!-- cd-timeline-content -->
                    </div> <!-- cd-timeline-block -->

                    <div class="cd-timeline-block">
                        <div class="cd-timeline-img cd-movie">
                             
                        </div> <!-- cd-timeline-img -->

                        <div class="cd-timeline-content">
                            <h2>Nhận huân chương lao động hạng ba</h2>
                            
                            <p>Đoạn Thông tin tín hiệu Đà Nẵng vinh dự được Chủ tịch hội đồng Nhà nước trao tặng huân chương Lao Động hạng ba</p>
                            <span class="cd-date">1982</span>
                        </div> <!-- cd-timeline-content -->
                    </div> <!-- cd-timeline-block -->

                    <div class="cd-timeline-block">
                        
                        <div class="cd-timeline-img cd-location">
                        </div> <!-- cd-timeline-img -->

                        <div class="cd-timeline-content">
                            <h2>Thành lập công ty</h2>
                            <p>Thành lập đoạn Thông tin tín hiệu Đà Nẵng</p>
                            <span class="cd-date">02/05/1979</span>
                        </div> <!-- cd-timeline-content -->
                    </div> <!-- cd-timeline-block -->
                </section> <!-- cd-timeline -->
            </div>
            <div class="col-md-4 pull-right">
                <div class=" block padding_right5">
                    <div class="search">
                        <input type="text" class="form-control input-search" maxlength="64" placeholder="Tìm kiếm" />
                        <button type="submit" class="btn btn-primary btn-search"><i class="fa fa-search"></i><p>Tìm kiếm</p></button>
                    </div>
                </div>    
                <div class="block">
                
                <?php $this->blkLatestNews(); ?>
            
                </div>

                <div class="block">
                    <?php $this->blkVideo();?>
                </div>
                
            </div>
            
        </div>
    </div> 
<div class="col-sm-8">
    

</div>
