<?php
$urlCSS_DSDN = URL_TEMPLATE . '/frontend_dsdn/css';
$urlJS_DSDN = URL_TEMPLATE . '/frontend_dsdn/js';
$urlImage_DSDN = URL_TEMPLATE . '/frontend_dsdn/img';

use Zend\Session\Container;

$ssSystem = new Container('system');
$helperString = new \Ocoder\Helper\String;

?>
 <div class="row">
        <div class="container contact-content" style="padding: 0">
            <img src="<?php echo $urlImage_DSDN?>/news.jpg" alt="">   
            <p class="contact_p">Tin Tức</p>
        </div>

    </div>
    <div class="row page-default ">
        <div class="container content">
            <div class="breakum-line">
                <a href="<?php echo URL_APPLICATION ?>"><?php echo HOME ?></a>/<span> Lịch sử phát triển</span>
            </div>
        
            <div class="col-md-8 ">
                <div class="row-member block">
                    <div class="row-line">
                        <span class="title-default">THÀNH VIÊN HỘI ĐỒNG QUẢN TRỊ</span>
                    </div>
                    <div class="uc_owl_carousel" id="uc_carousel_testimonials1">
                        <!--item 1-->
                        <div class="uc_item">
                            <div class=" post">
                                <!-- start of  menber box block -->
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/1.jpg" alt="MR. ANH NGUYEN" />
                                        <!-- start of social icon block -->
                                        <div class="uc_overlay">
                                            <div class="uc_overlay_inner">
                                                <div class="uc_social_row">
                                                    <ul class="uc_social_link">
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-facebook"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-twitter"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-instagram"></i><span></span></a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end of social icon  block -->
                                    </div>
                                    <!-- start of content block -->
                                    <div class="uc_paragraph">
                                        <h3 class="uc_tittle">MR. ANH NGUYEN </h3>
                                        <small>DIRECTOR</small>
                                    </div>
                                    <!-- end of content block -->
                                </div>
                                <!-- end of  menber box block -->
                            </div>
                        </div>
                        <!-- end item 1-->
                        <!--item 2-->
                        <div class="uc_item">
                            <div class=" post">
                                <!-- start of  menber box block -->
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/3.jpg" alt="MR. THAI TRAN" />
                                        <!-- start of social icon block -->
                                        <div class="uc_overlay">
                                            <div class="uc_overlay_inner">
                                                <div class="uc_social_row">
                                                    <ul class="uc_social_link">
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-facebook"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-twitter"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-instagram"></i><span></span></a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end of social icon  block -->
                                    </div>
                                    <!-- start of content block -->
                                    <div class="uc_paragraph">
                                        <div class="name-human">
                                             <h3 class="uc_tittle">MR. THAI TRAN</h3>
                                        </div>
                                        <small>MANAGER</small>
                                    
                                    </div>
                                    <!-- end of content block -->
                                </div>
                                <!-- end of  menber box block -->
                            </div>
                        </div>
                        <!-- end item 2-->
                        <!--item 3-->
                        <div class="uc_item">
                            <div class=" post">
                                <!-- start of  menber box block -->
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/2.jpg" alt="MIS. LAN HOA" />
                                        <!-- start of social icon block -->
                                        <div class="uc_overlay">
                                            <div class="uc_overlay_inner">
                                                <div class="uc_social_row">
                                                    <ul class="uc_social_link">
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-facebook"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-twitter"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-instagram"></i><span></span></a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end of social icon  block -->
                                    </div>
                                    <!-- start of content block -->
                                    <div class="uc_paragraph">
                                        <h3 class="uc_tittle">MIS. LAN HOA</h3>
                                        <small>DEPUTY</small>
                                    </div>
                                    <!-- end of content block -->
                                </div>
                                <!-- end of  menber box block -->
                            </div>
                        </div>
                        <!-- end item 3-->
                        <!--item 3-->
                        <div class="uc_item">
                            <div class=" post">
                                <!-- start of  menber box block -->
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/7.jpg" alt="MR. TUAN ANH" />
                                        <!-- start of social icon block -->
                                        <div class="uc_overlay">
                                            <div class="uc_overlay_inner">
                                                <div class="uc_social_row">
                                                    <ul class="uc_social_link">
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-facebook"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-twitter"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-instagram"></i><span></span></a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end of social icon  block -->
                                    </div>
                                    <!-- start of content block -->
                                    <div class="uc_paragraph">
                                        <h3 class="uc_tittle">MR. TUAN ANH </h3>
                                        <small>DESIGNER</small>
            
                                    </div>
                                    <!-- end of content block -->
                                </div>
                                <!-- end of  menber box block -->
                            </div>
                        </div>
                        <!-- end item 3-->
                        <!--item 3-->
                        <div class="uc_item">
                            <div class=" post">
                                <!-- start of  menber box block -->
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/5.jpg" alt="MR. HUONG PHAM" />
                                        <!-- start of social icon block -->
                                        <div class="uc_overlay">
                                            <div class="uc_overlay_inner">
                                                <div class="uc_social_row">
                                                    <ul class="uc_social_link">
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-facebook"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-twitter"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-instagram"></i><span></span></a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end of social icon  block -->
                                    </div>
                                    <!-- start of content block -->
                                    <div class="uc_paragraph">
                                        <h3 class="uc_tittle">MR. HUONG PHAM</h3>
                                        <small>ACCOUNTANT</small>
                                    </div>
                                    <!-- end of content block -->
                                </div>
                                <!-- end of  menber box block -->
                            </div>
                        </div>
                        <!-- end item 3-->
                        <!--item 3-->
                        <div class="uc_item">
                            <div class=" post">
                                <!-- start of  menber box block -->
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/6.jpg" alt="MISS QUYNH NHU" />
                                        <!-- start of social icon block -->
                                        <div class="uc_overlay">
                                            <div class="uc_overlay_inner">
                                                <div class="uc_social_row">
                                                    <ul class="uc_social_link">
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-facebook"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-twitter"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-instagram"></i><span></span></a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end of social icon  block -->
                                    </div>
                                    <!-- start of content block -->
                                    <div class="uc_paragraph">
                                        <h3 class="uc_tittle">MISS QUYNH NHU </h3>
                                        <small>SECRETARY</small>
                                    </div>
                                    <!-- end of content block -->
                                </div>
                                <!-- end of  menber box block -->
                            </div>
                        </div>
                        <!-- end item 3-->
                    </div>
                </div>

            
                <div class="row-member block">
                    <div class="row-line">
                        <span class="title-default">THÀNH VIÊN HỘI ĐỒNG QUẢN TRỊ</span>
                    </div>
                    <div class="uc_owl_carousel" id="uc_carousel_testimonials2">
                        <!--item 1-->
                        <div class="uc_item">
                            <div class=" post">
                                <!-- start of  menber box block -->
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/1.jpg" alt="MR. ANH NGUYEN" />
                                        <!-- start of social icon block -->
                                        <div class="uc_overlay">
                                            <div class="uc_overlay_inner">
                                                <div class="uc_social_row">
                                                    <ul class="uc_social_link">
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-facebook"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-twitter"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-instagram"></i><span></span></a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end of social icon  block -->
                                    </div>
                                    <!-- start of content block -->
                                    <div class="uc_paragraph">
                                        <h3 class="uc_tittle">MR. ANH NGUYEN </h3>
                                        <small>DIRECTOR</small>
                                    </div>
                                    <!-- end of content block -->
                                </div>
                                <!-- end of  menber box block -->
                            </div>
                        </div>
                        <!-- end item 1-->
                        <!--item 2-->
                        <div class="uc_item">
                            <div class=" post">
                                <!-- start of  menber box block -->
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/3.jpg" alt="MR. THAI TRAN" />
                                        <!-- start of social icon block -->
                                        <div class="uc_overlay">
                                            <div class="uc_overlay_inner">
                                                <div class="uc_social_row">
                                                    <ul class="uc_social_link">
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-facebook"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-twitter"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-instagram"></i><span></span></a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end of social icon  block -->
                                    </div>
                                    <!-- start of content block -->
                                    <div class="uc_paragraph">
                                        <div class="name-human">
                                             <h3 class="uc_tittle">MR. THAI TRAN</h3>
                                        </div>
                                        <small>MANAGER</small>
                                    
                                    </div>
                                    <!-- end of content block -->
                                </div>
                                <!-- end of  menber box block -->
                            </div>
                        </div>
                        <!-- end item 2-->
                        <!--item 3-->
                        <div class="uc_item">
                            <div class=" post">
                                <!-- start of  menber box block -->
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/2.jpg" alt="MIS. LAN HOA" />
                                        <!-- start of social icon block -->
                                        <div class="uc_overlay">
                                            <div class="uc_overlay_inner">
                                                <div class="uc_social_row">
                                                    <ul class="uc_social_link">
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-facebook"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-twitter"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-instagram"></i><span></span></a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end of social icon  block -->
                                    </div>
                                    <!-- start of content block -->
                                    <div class="uc_paragraph">
                                        <h3 class="uc_tittle">MIS. LAN HOA</h3>
                                        <small>DEPUTY</small>
                                    </div>
                                    <!-- end of content block -->
                                </div>
                                <!-- end of  menber box block -->
                            </div>
                        </div>
                        <!-- end item 3-->
                        <!--item 3-->
                        <div class="uc_item">
                            <div class=" post">
                                <!-- start of  menber box block -->
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/7.jpg" alt="MR. TUAN ANH" />
                                        <!-- start of social icon block -->
                                        <div class="uc_overlay">
                                            <div class="uc_overlay_inner">
                                                <div class="uc_social_row">
                                                    <ul class="uc_social_link">
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-facebook"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-twitter"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-instagram"></i><span></span></a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end of social icon  block -->
                                    </div>
                                    <!-- start of content block -->
                                    <div class="uc_paragraph">
                                        <h3 class="uc_tittle">MR. TUAN ANH </h3>
                                        <small>DESIGNER</small>
            
                                    </div>
                                    <!-- end of content block -->
                                </div>
                                <!-- end of  menber box block -->
                            </div>
                        </div>
                        <!-- end item 3-->
                        <!--item 3-->
                        <div class="uc_item">
                            <div class=" post">
                                <!-- start of  menber box block -->
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/5.jpg" alt="MR. HUONG PHAM" />
                                        <!-- start of social icon block -->
                                        <div class="uc_overlay">
                                            <div class="uc_overlay_inner">
                                                <div class="uc_social_row">
                                                    <ul class="uc_social_link">
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-facebook"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-twitter"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-instagram"></i><span></span></a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end of social icon  block -->
                                    </div>
                                    <!-- start of content block -->
                                    <div class="uc_paragraph">
                                        <h3 class="uc_tittle">MR. HUONG PHAM</h3>
                                        <small>ACCOUNTANT</small>
                                    </div>
                                    <!-- end of content block -->
                                </div>
                                <!-- end of  menber box block -->
                            </div>
                        </div>
                        <!-- end item 3-->
                        <!--item 3-->
                        <div class="uc_item">
                            <div class=" post">
                                <!-- start of  menber box block -->
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/6.jpg" alt="MISS QUYNH NHU" />
                                        <!-- start of social icon block -->
                                        <div class="uc_overlay">
                                            <div class="uc_overlay_inner">
                                                <div class="uc_social_row">
                                                    <ul class="uc_social_link">
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-facebook"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-twitter"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-instagram"></i><span></span></a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end of social icon  block -->
                                    </div>
                                    <!-- start of content block -->
                                    <div class="uc_paragraph">
                                        <h3 class="uc_tittle">MISS QUYNH NHU </h3>
                                        <small>SECRETARY</small>
                                    </div>
                                    <!-- end of content block -->
                                </div>
                                <!-- end of  menber box block -->
                            </div>
                        </div>
                        <!-- end item 3-->
                    </div>
                </div>
                        
            
                <div class="row-member">
                    <div class="row-line">
                        <span class="title-default">THÀNH VIÊN HỘI ĐỒNG QUẢN TRỊ</span>
                    </div>
                    <div class="uc_owl_carousel" id="uc_carousel_testimonials3">
                        <!--item 1-->
                        <div class="uc_item">
                            <div class=" post">
                                <!-- start of  menber box block -->
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/1.jpg" alt="MR. ANH NGUYEN" />
                                        <!-- start of social icon block -->
                                        <div class="uc_overlay">
                                            <div class="uc_overlay_inner">
                                                <div class="uc_social_row">
                                                    <ul class="uc_social_link">
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-facebook"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-twitter"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-instagram"></i><span></span></a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end of social icon  block -->
                                    </div>
                                    <!-- start of content block -->
                                    <div class="uc_paragraph">
                                        <h3 class="uc_tittle">MR. ANH NGUYEN </h3>
                                        <small>DIRECTOR</small>
                                    </div>
                                    <!-- end of content block -->
                                </div>
                                <!-- end of  menber box block -->
                            </div>
                        </div>
                        <!-- end item 1-->
                        <!--item 2-->
                        <div class="uc_item">
                            <div class=" post">
                                <!-- start of  menber box block -->
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/3.jpg" alt="MR. THAI TRAN" />
                                        <!-- start of social icon block -->
                                        <div class="uc_overlay">
                                            <div class="uc_overlay_inner">
                                                <div class="uc_social_row">
                                                    <ul class="uc_social_link">
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-facebook"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-twitter"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-instagram"></i><span></span></a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end of social icon  block -->
                                    </div>
                                    <!-- start of content block -->
                                    <div class="uc_paragraph">
                                        <div class="name-human">
                                             <h3 class="uc_tittle">MR. THAI TRAN</h3>
                                        </div>
                                        <small>MANAGER</small>
                                    
                                    </div>
                                    <!-- end of content block -->
                                </div>
                                <!-- end of  menber box block -->
                            </div>
                        </div>
                        <!-- end item 2-->
                        <!--item 3-->
                        <div class="uc_item">
                            <div class=" post">
                                <!-- start of  menber box block -->
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/2.jpg" alt="MIS. LAN HOA" />
                                        <!-- start of social icon block -->
                                        <div class="uc_overlay">
                                            <div class="uc_overlay_inner">
                                                <div class="uc_social_row">
                                                    <ul class="uc_social_link">
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-facebook"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-twitter"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-instagram"></i><span></span></a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end of social icon  block -->
                                    </div>
                                    <!-- start of content block -->
                                    <div class="uc_paragraph">
                                        <h3 class="uc_tittle">MIS. LAN HOA</h3>
                                        <small>DEPUTY</small>
                                    </div>
                                    <!-- end of content block -->
                                </div>
                                <!-- end of  menber box block -->
                            </div>
                        </div>
                        <!-- end item 3-->
                        <!--item 3-->
                        <div class="uc_item">
                            <div class=" post">
                                <!-- start of  menber box block -->
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/7.jpg" alt="MR. TUAN ANH" />
                                        <!-- start of social icon block -->
                                        <div class="uc_overlay">
                                            <div class="uc_overlay_inner">
                                                <div class="uc_social_row">
                                                    <ul class="uc_social_link">
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-facebook"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-twitter"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-instagram"></i><span></span></a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end of social icon  block -->
                                    </div>
                                    <!-- start of content block -->
                                    <div class="uc_paragraph">
                                        <h3 class="uc_tittle">MR. TUAN ANH </h3>
                                        <small>DESIGNER</small>
            
                                    </div>
                                    <!-- end of content block -->
                                </div>
                                <!-- end of  menber box block -->
                            </div>
                        </div>
                        <!-- end item 3-->
                        <!--item 3-->
                        <div class="uc_item">
                            <div class=" post">
                                <!-- start of  menber box block -->
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/5.jpg" alt="MR. HUONG PHAM" />
                                        <!-- start of social icon block -->
                                        <div class="uc_overlay">
                                            <div class="uc_overlay_inner">
                                                <div class="uc_social_row">
                                                    <ul class="uc_social_link">
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-facebook"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-twitter"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-instagram"></i><span></span></a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end of social icon  block -->
                                    </div>
                                    <!-- start of content block -->
                                    <div class="uc_paragraph">
                                        <h3 class="uc_tittle">MR. HUONG PHAM</h3>
                                        <small>ACCOUNTANT</small>
                                    </div>
                                    <!-- end of content block -->
                                </div>
                                <!-- end of  menber box block -->
                            </div>
                        </div>
                        <!-- end item 3-->
                        <!--item 3-->
                        <div class="uc_item">
                            <div class=" post">
                                <!-- start of  menber box block -->
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/6.jpg" alt="MISS QUYNH NHU" />
                                        <!-- start of social icon block -->
                                        <div class="uc_overlay">
                                            <div class="uc_overlay_inner">
                                                <div class="uc_social_row">
                                                    <ul class="uc_social_link">
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-facebook"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-twitter"></i><span></span></a></li>
                                                        <li><a href="#" class="uc_social_icon"><i class="fa fa-instagram"></i><span></span></a>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end of social icon  block -->
                                    </div>
                                    <!-- start of content block -->
                                    <div class="uc_paragraph">
                                        <h3 class="uc_tittle">MISS QUYNH NHU </h3>
                                        <small>SECRETARY</small>
                                    </div>
                                    <!-- end of content block -->
                                </div>
                                <!-- end of  menber box block -->
                            </div>
                        </div>
                        <!-- end item 3-->
                    </div>
                </div>
                        
            </div>
            <div class="col-md-4 pull-right">
                <div class=" block padding_right5">
                    <div class="search">
                        <input type="text" class="form-control input-search" maxlength="64" placeholder="Tìm kiếm" />
                        <button type="submit" class="btn btn-primary btn-search"><i class="fa fa-search"></i><p>Tìm kiếm</p></button>
                    </div>
                </div>    
                <div class="block">
                
                <?php $this->blkLatestNews(); ?>
            
                </div>

                <div class="block">
                    <?php $this->blkVideo();?>
                </div>
                
            </div>
            
        </div>
    </div> 

