<?php
$urlCSS_DSDN = URL_TEMPLATE . '/frontend_dsdn/css';
$urlJS_DSDN = URL_TEMPLATE . '/frontend_dsdn/js';
$urlImage_DSDN = URL_TEMPLATE . '/frontend_dsdn/img';

use Zend\Session\Container;

$ssSystem = new Container('system');
$helperString = new \Ocoder\Helper\String;

?>
 <div class="row">
        <div class="container contact-content" style="padding: 0">
            <img src="<?php echo $urlImage_DSDN?>/news.jpg" alt="">   
            <p class="contact_p">Tin Tức</p>
        </div>

    </div>
    <div class="row page-default ">
        <div class="container content">
            <div class="breakum-line">
                <a href="<?php echo URL_APPLICATION ?>"><?php echo HOME ?></a>/<span> Lịch sử phát triển</span>
            </div>
        
            <div class="col-md-8 ">
                <div class="row-member">
                    <div class="row-line">
                        <span class="title-default">THÀNH VIÊN HỘI ĐỒNG QUẢN TRỊ</span>
                    </div>
                    <div class="uc_owl_carousel" id="uc_carousel_testimonials1">
                               
                        <div class="uc_item">
                            <div class=" post">
                              
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/5.jpg" alt="Ông.Phí Đình Thái" />
                                    </div>
                                 
                                    <div class="uc_paragraph">
                                        <h3 class="uc_tittle">Ông Phí Đình Thái </h3>
                                        <small>Chủ tịch Hội đồng quản trị</small>
                                    </div>
                                    
                                </div>
                                
                            </div>
                        </div>
                               
                        <div class="uc_item">
                            <div class=" post">
                               
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/7.jpg" alt="Ông Nguyễn Ngọc Trãi" />
                                    </div>
                                   
                                    <div class="uc_paragraph">
                                        <div class="name-human">
                                             <h3 class="uc_tittle">Ông Nguyễn Ngọc Trãi </h3>
                                        </div>
                                        <small>GIÁM ĐỐC CÔNG TY</small>
                                    
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="uc_item">
                            <div class=" post">
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/3.jpg" alt="Ông Lê Đình Hùng" />
                                    </div>
                                   
                                    <div class="uc_paragraph">
                                        <h3 class="uc_tittle">Ông Lê Đình Hùng </h3>
                                        <small>Thành viên trực thuộc</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row-member">
                    <div class="row-line">
                        <span class="title-default">THÀNH VIÊN BAN GIÁM ĐỐC</span>
                    </div>
                    <div class="uc_owl_carousel" id="uc_carousel_testimonials2">
                      
                        <div class="uc_item">
                            <div class=" post"><!-- start of  menber box block -->
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/1.jpg" alt="Ông Nguyễn Xuân Chí" />
                                    </div>
                                    
                                    <div class="uc_paragraph">
                                        <h3 class="uc_tittle">Ông Nguyễn Xuân Chí </h3>
                                        <small>Phó giám đốc công ty</small>
                                    </div>
                                    
                                </div>
                                
                            </div>
                        </div>
                        
                        <div class="uc_item">
                            <div class=" post">
                              
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/3.jpg" alt="Ông Nguyễn Mạnh Hải" />
                                    </div>
                                   
                                    <div class="uc_paragraph">
                                        <div class="name-human">
                                             <h3 class="uc_tittle">Ông Nguyễn Mạnh Hải </h3>
                                        </div>
                                        <small>Phó giám đốc công ty</small>
                                    
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row-member">
                    <div class="row-line">
                        <span class="title-default">THÀNH VIÊN BAN KIỂM SOÁT</span>
                    </div>
                    <div class="uc_owl_carousel" id="uc_carousel_testimonials3">
                       
                        <div class="uc_item">
                            <div class=" post">
                               
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/7.jpg" alt="Ông Lê Viết Chiến" />
                                    </div>
                                   
                                    <div class="uc_paragraph">
                                        <h3 class="uc_tittle">Ông Lê Viết Chiến</h3>
                                        <small>Trưởng ban kiểm soát</small>
                                    </div>
                                    
                                </div>
                               
                            </div>
                        </div>
                       
                        <div class="uc_item">
                            <div class=" post">
                               
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/3.jpg" alt="Ông Hán Doanh Minh" />
                                    </div>
                                   
                                    <div class="uc_paragraph">
                                        <div class="name-human">
                                             <h3 class="uc_tittle">Ông Hán Doanh Minh</h3>
                                        </div>
                                        <small>Thành viên</small>
                                    
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="uc_item">
                            <div class=" post">
                               
                                <div class="uc_member_hover_effect">
                                    <div class="uc_box_image">
                                        <img src="<?php echo $urlImage_DSDN ?>/icon-human/4.jpg" alt="Bà Nguyễn Thị Nguyên Quế" />
                                    </div>
                                   
                                    <div class="uc_paragraph">
                                        <div class="name-human">
                                             <h3 class="uc_tittle">Bà Nguyễn Thị Nguyên Quế </h3>
                                        </div>
                                        <small>Thành viên</small>
                                    
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 pull-right">
                <div class=" block padding_right5">
                    <div class="search">
                        <input type="text" class="form-control input-search" maxlength="64" placeholder="Tìm kiếm" />
                        <button type="submit" class="btn btn-primary btn-search"><i class="fa fa-search"></i><p>Tìm kiếm</p></button>
                    </div>
                </div>    
                <div class="block">
                
                <?php $this->blkLatestNews(); ?>
            
                </div>

                <div class="block">
                    <?php $this->blkVideo();?>
                </div>
                
            </div>
            
        </div>
    </div> 

