<?php

use Zend\Session\Container;

$ssSystem = new Container('system');
$helperString = new \Ocoder\Helper\String;
?>


                <!--<div class="col-sm-5">
                    <a href="<?php// echo URL_APPLICATION . '/bv/' . $alias ?>">
                        <!--<img src="<?php //echo $imageUrl ?>" alt="<?php //echo $name ?>" class="img-responsive">
                    </a>
                <!--</div>
                <div class="content col-sm-7">
                    <a href="<?php// echo URL_APPLICATION . '/bv/' . $alias ?>"><?php //echo $helperString->summary($name, 20, true); ?></a>
                    <p><?php //echo $helperString->summary($intro, 80, true, true); ?></p>
                <!--</div>
            </div>
        <?php //} ?>
    </div>
</div><!-- END Sidebar Right Featured News -->
<div class="tinanh">
    <span class="tittle"><?php echo LASTEST_NEWS ?></span>
    <?php foreach ($this->_data as $item) {?>
        <div class="items">    
         <?php
            if ($ssSystem->language == DEFAULT_LANGUAGE) {
                $name = $item->name;
                $intro = $item->intro;
                $alias = $item->alias;
                } else {
                    $nameLang = json_decode($item->name_lang);
                    $nameField = 'name_' . $ssSystem->language;
                    $name = $nameLang->$nameField;
                    $introLang = json_decode($item->intro_lang);
                    $introField = 'intro_' . $ssSystem->language;
                    $intro = $introLang->$introField;
                    $aliasLang = json_decode($item->alias_lang);
                    $aliasField = 'alias_' . $ssSystem->language;
                    $alias = $aliasLang->$aliasField;
                }

                if (trim($item->thumbnail) && $helperString->isUrlExist(URL_APPLICATION . $item->thumbnail)) {
                    $imageUrl = URL_APPLICATION . $item->thumbnail;
                } else {
                    $imageUrl = URL_TEMPLATE . '/frontend_dsdn/img/tinanh/no-image.png';
                }
                ?>       
    
    <a href="<?php echo URL_APPLICATION . '/bv/' . $alias ?>"><img src="<?php echo $imageUrl ?>" alt="Hoạt động công ty" title="" class="img"></a><a href="<?php echo URL_APPLICATION . '/bv/' . $alias ?>" title="Hoạt động công ty" class="newslink"><?php echo $helperString->summary($name, 100, true); ?></a><br>
   
    
    </div>
<?php } ?>
    <div class="link"><a href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_NEWS ?>" class="linkmore">Xem thêm </a></div>
</div>