<?php

use Zend\Session\Container;

$ssSystem = new Container('system');
$helperString = new \Ocoder\Helper\String;
?>

<!-- Main Content of Website -->
<div class="main-wrapper category-detail-page">
    <!-- Main Content -->
    <div class="row main-content-wrapper">
        <!-- Main Content -->
        <div class="main-content col-sm-8">
            <img src="<?php echo URL_TEMPLATE . '/frontend/images/banner-sub.jpg' ?>" class="img-thumbnail banner-sub">

            <!-- Category List -->
            <div class="row products">
                <?php
                if ($ssSystem->language == DEFAULT_LANGUAGE) {
                    $name = $categoryInfo->name;
                } else {
                    $nameLang = json_decode($categoryInfo->name_lang);
                    $nameField = 'name_' . $ssSystem->language;
                    $name = $nameLang->$nameField;
                }
                ?>
                <h3 class="col-sm-12 header-title"><span class="glyphicon glyphicon-th-large" aria-hidden="true"></span> <?php echo $name ?></h3>
                <?php
                foreach ($this->products as $product) {
                    if ($ssSystem->language == DEFAULT_LANGUAGE) {
                        $name = $product->name;
                        $alias = $product->alias;
                        $intro = $product->intro;
                    } else {
                        $nameLang = json_decode($product->name_lang);
                        $nameField = 'name_' . $ssSystem->language;
                        $name = $nameLang->$nameField;
                        $aliasLang = json_decode($product->alias_lang);
                        $aliasField = 'alias_' . $ssSystem->language;
                        $alias = $aliasLang->$aliasField;
                        $introLang = json_decode($product->intro_lang);
                        $introField = 'intro_' . $ssSystem->language;
                        $intro = $introLang->$introField;
                    }

                    if (trim($product->picture) && $helperString->isUrlExist(URL_APPLICATION . $product->picture)) {
                        $imageUrl = URL_APPLICATION . $product->picture;
                    } else {
                        $imageUrl = URL_TEMPLATE . '/frontend/images/no-image.png';
                    }
                    ?>
                    <div class="col-sm-6 product-item">
                        <div class="product-thumbnail effect-box-shadow">
                            <a href="<?php echo URL_APPLICATION . '/sp/' . $alias; ?>">
                                <img src="<?php echo $imageUrl ?>" alt="<?php echo $name ?>" class="img-thumbnail">
                            </a>
                        </div>
                        <div>
                            <h3 class="product-name"><a href="<?php echo URL_APPLICATION . '/sp/' . $alias; ?>"><?php echo $helperString->summary($name, 50, true, true); ?></a></h3>
                            <p class="price"><strong><?php echo PRICE ?>: <span><?php echo number_format($product->price, 0, ',', '.') . " VND" ?></span></strong></p>
                            <p class="short-desc"><?php echo $helperString->summary($intro, 150, true, true); ?></p>
                        </div>
                    </div>   
                <?php } ?>
            </div>
        </div>

        <!-- Sidebar right -->
        <div class="sidebar-right col-sm-4">
            <?php
            // Sidebar Right Product Category Block
            echo $this->blkProductCategory();
            // Sidebar Right Services Block
            echo $this->blkServices();
            // Sidebar Right Video Block
            echo $this->blkVideo();
            // Sidebar Right Featured News
            echo $this->blkLatestNews();
            ?>
        </div><!-- Sidebar Right -->
    </div><!-- End Main Content -->

    <!-- PAGINATION -->
    <?php
//    $aliasCategory = array(
//        COMPANY_INFO_CATEGORY_ID => '/gioi-thieu',
//        SERVICE_CATEGORY_ID => '/dich-vu',
//        RECRUITMENT_CATEGORY_ID => '/tuyen-dung',
//    );
//    $currentURL = URL_APPLICATION . $aliasCategory[$this->categoryInfo->id];
//    echo $this->paginationControl($this->paginator, 'sliding', 'paginator.phtml', array('currentURL' => $currentURL));
    ?>