<?php

use Zend\Session\Container;

$ssSystem = new Container('system');
$helperString = new \Ocoder\Helper\String;
?>

<!-- Main Content of Website -->
<div class="main-wrapper product-page">
    <!-- Main Content -->
    <div class="row main-content-wrapper">
        <!-- Main Content -->
        <div class="main-content col-sm-8">
            <?php
            if ($ssSystem->language == DEFAULT_LANGUAGE) {
                $name = $this->productInfo->name;
                $intro = $this->productInfo->intro;
                $description = $this->productInfo->description;
            } else {
                $nameLang = json_decode($this->productInfo->name_lang);
                $nameField = 'name_' . $ssSystem->language;
                $name = $nameLang->$nameField;
                $introLang = json_decode($this->productInfo->intro_lang);
                $introField = 'intro_' . $ssSystem->language;
                $intro = $introLang->$introField;
                $descriptionLang = json_decode($this->productInfo->description_lang);
                $descriptionField = 'description_' . $ssSystem->language;
                $description = $descriptionLang->$descriptionField;
            }

            if (trim($this->productInfo->picture) && $helperString->isUrlExist(URL_APPLICATION . $this->productInfo->picture)) {
                $imageUrl = URL_APPLICATION . $this->productInfo->picture;
            } else {
                $imageUrl = URL_TEMPLATE . '/frontend/images/no-image.png';
            }
            ?>
            <img src="<?php echo URL_TEMPLATE . '/frontend/images/banner-sub.jpg' ?>" class="img-thumbnail banner-sub">

            <!-- Category List -->
            <div class="row">
                <h3 class="col-sm-12 header-title"><span class="glyphicon glyphicon-th-large" aria-hidden="true"></span> <?php echo $name ?></h3>
                <div class="col-sm-6">
                    <img src="<?php echo $imageUrl ?>" alt="<?php echo $name ?>" class="img-thumbnail product-thumbnail">
                </div>
                <div class="col-sm-6">
                    <div style="margin-bottom: 10px;">
                        <strong><?php echo PRICE ?>: <span style="color: #f00"><?php echo number_format($this->productInfo->price, 0, ',', '.') . " VND" ?></span></strong>
                    </div>
                    <div>
                        <?php echo $intro ?>
                    </div>
                </div>
                <div class="col-sm-12">
                    <h3 class="col-sm-12 header-title" style="padding: 0"><?php echo PRODUCT_DESCRIPTION ?></h3>
                    <div>
                        <?php echo $description ?>
                    </div>
                </div>
            </div>
        </div>

        <!-- Sidebar right -->
        <div class="sidebar-right col-sm-4">
            <?php
            // Sidebar Right Product Category Block
            echo $this->blkProductCategory();
            // Sidebar Right Services Block
            echo $this->blkServices();
            // Sidebar Right Video Block
            echo $this->blkVideo();
            // Sidebar Right Featured News
            echo $this->blkLatestNews();
            ?>
        </div><!-- Sidebar Right -->
    </div><!-- End Main Content -->

    <!-- PAGINATION -->
    <?php
//    $aliasCategory = array(
//        COMPANY_INFO_CATEGORY_ID => '/gioi-thieu',
//        SERVICE_CATEGORY_ID => '/dich-vu',
//        RECRUITMENT_CATEGORY_ID => '/tuyen-dung',
//    );
//    $currentURL = URL_APPLICATION . $aliasCategory[$this->categoryInfo->id];
//    echo $this->paginationControl($this->paginator, 'sliding', 'paginator.phtml', array('currentURL' => $currentURL));
    ?>