<!-- Footer block-->
    <footer class="bs-docs-footer" role="contentinfo">
        <div class="container-1">
            <div class="row">
                <div class="container">
                    
                    <div class="col-md-6 col-sm-6">
                         <div class="social-block  pull-left">
                            <h4><?php echo $ssSystem->configs->company_name;?></h4>
                            <div>
                                <div class="address">
                                    
                                    <i class="fa fa-home" aria-hidden="true"></i>  
                                    <p><?php echo $ssSystem->configs->company_address;?></p>
                                </div>
                                <div class="contact-phone">
                                    
                                    <i class="fa fa-phone" aria-hidden="true"></i>
                                    <p class="sdt"><?php echo $ssSystem->configs->company_phone;?></p>
                                </div>
                            </div>
                        </div>
                    </div><div class="col-md-6 col-sm-6 social">
                        <div class="social-block">
                            <h4 class="float-left">Kết nối:</h4>
                            <div>
                                <a href="#">
                                    <i class="fa fa-facebook-official" aria-hidden="true"></i>
                                </a>
                                <a href="#">
                                    <i class="fa fa-youtube" aria-hidden="true"></i>
                                </a>
                                <a href="#">
                                   <i class="fa fa-google-plus-square" aria-hidden="true"></i>
                                </a>
                            </div>
                           
                            <div class="social-block text-center">
                                <span class="copyright">
                                    <p class="copyright_line">Copyright © 2016  | Bản quyền thuộc về : <?php echo $ssSystem->configs->company_name;?></p>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-2 copyright center">
             <div class="row">
                <div class="col-md-8  col-md-offset-2 col-xs-10 col-xs-offset-1">
                        
                </div>
                
            </div>
        </div>
    </footer>
    
    <!-- js occodion in maincontent-->
    <script src="<?php echo $urlJS_DSDN ?>/jquery-ui.js"></script>
    <script src="<?php echo $urlJS_DSDN ?>/owl.carousel.min.js" type="text/javascript"></script>
    <!-- main js file -->
    <script src="<?php echo $urlJS_DSDN ?>/main.js"></script>
     <script src="<?php echo $urlJS_DSDN ?>/timeline.js"></script>