<?php 
use Zend\Session\Container;
$ssSystem = new Container('system');
?>
<header>
    <div class="header-wrapper container">
        <div class="row">
            <div class="container">
            
                <div id="text-2" class="widget_text">
                    <div class="textwidget">
                        <div class="logo col-sm-3 col-xs-3">
                            <a class="home-link" href="<?php echo URL_APPLICATION ?>" title="" rel="home">
                            <img class="img-rize" src="<?php echo URL_APPLICATION . $ssSystem->configs->logo ?>" alt="logo">
                            </a>
                        </div>
                        <div class="phone col-sm-9 col-xs-9">
                            <div class="content">
                                <span class="title"><?php echo $ssSystem->configs->action_title ?></span><br>
                                <span class="phone-number"><?php echo $ssSystem->configs->company_phone ?></span><br>
                                <span class="wrt"><?php echo $ssSystem->configs->company_name ?></span><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

        <div class="container menu-main">
            <div class="navbar-header">
               <!-- <div id="text-4" class="widget_text">
                    <div class="textwidget"><a href="<?php //echo URL_APPLICATION ?>" class="request-quote">Trang chủ</a></div>
                </div>-->
                <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
            </div>
            <nav class="collapse navbar-collapse bs-navbar-collapse">
                
                <ul class="parent nav navbar-nav">
                     <li class="parent-item ">
                       <a href="<?php echo URL_APPLICATION ?>" ><?php echo HOME ?></a>
                    </li>
                    <li class="parent-item dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_INTRO ?>"><?php echo INTRO ?> <span class="caret"></span></a>
                         <ul class="dropdown-menu">
                            <li><a href="<?php echo URL_APPLICATION ?>/bv/ve-cong-ty-39">Về Công ty</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/bv/lich-su-phat-trien-40">Lịch sử phát triển</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/bv/so-do-to-chuc-41">Sơ đồ tổ chức</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/bv/nhan-su-chu-chot-42">Nhân sự chủ chốt</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/bv/don-vi-thanh-vien-43">Đơn vị thành viên</a></li>
                        </ul>
                    </li>
                    <li class="parent-item dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_SERVICE ?>">Dịch vụ <span class="caret"></span></a>
                         <ul class="dropdown-menu">
                            <li><a href="<?php echo URL_APPLICATION ?>/bv/quan-ly-bao-tri-1">Quản lý - Bảo trì</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/bv/tu-van-xay-dung-cong-trinh-2">Tư vấn -  Xây dựng</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/bv/san-xuatsua-chua-6">Sản xuất - sửa chữa</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/bv/cac-dich-vu-khac-7">Các Dịch vụ khác</a></li>
                        </ul>
                    </li>
                    <li class="parent-item dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_NEWS?>"><?php echo NEWS?> <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_NEWS?>/tin-nganh-duong-sat-7">Tin ngành đường sắt</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_NEWS?>/tin-noi-bo-8">Tin nội bộ</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_NEWS?>/tin-tuyen-dung-9">Tin tuyển dụng</a></li>
                        </ul>
                    </li>
                    <li class="parent-item ">
                        <a href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_DOCUMENT ?>">Công văn</a>
                    </li>
                    <!--<li class="parent-item ">
                        <a href="<?php //echo URL_APPLICATION ?>/<?php //echo URL_ALIAS_MEMBERS ?>"><?php //echo MEMBERS ?></a>
                    </li>-->
                    <li class="parent-item dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_SHAREHOLDER ?>"><?php echo SHAREHOLDER ?> <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_SHAREHOLDER?>/dai-hoi-co-dong-12">Đại Hội Cổ Đông</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_SHAREHOLDER?>/thong-bao-co-dong-13">Thông Báo Cổ Đông</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_SHAREHOLDER?>/bao-cao-thuong-nien-14">Báo Cáo thường Niên</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_SHAREHOLDER?>/thong-tin-tai-chinh-15">Thông tin tài chính</a></li>
                           
                        </ul>
                    </li>
                    <li class="parent-item ">
                        <a href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_CONTACT ?>"><?php echo CONTACT ?></a>
                    </li>
                </ul>
            </nav>
        </div>
