<?php 
use Zend\Session\Container;
$ssSystem = new Container('system');
?>
<header>
    <div class="header-wrapper container">
        <div class="row">
            <div class="container">
                <div id="text-2" class="widget_text">
                    <div class="textwidget">
                        <div class="logo col-sm-4 col-xs-6">
                            <a class="home-link" href="<?php echo URL_APPLICATION ?>" title="First Choice Restoration" rel="home">
                            <img class="img-rize" src="<?php echo URL_APPLICATION . $ssSystem->configs->logo ?>" alt="logo">
                            </a>
                        </div>
                        <div class="phone col-sm-8 col-xs-6">
                            <div class="content">
                                <span class="title">Gọi ngay hôm nay</span><br>
                                <span class="phone-number">(0511)3825472</span><br>
                                <span class="wrt">Công Ty CP Thông Tin Tín Hiệu Đường Sắt Đà Nẵng</span><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="menu-main">
        <div class="container">
            <div class="navbar-header">
                <div id="text-4" class="widget_text">
                    <div class="textwidget"><a href="<?php echo URL_APPLICATION ?>" class="request-quote">Trang chủ</a></div>
                </div>
                <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
            </div>
            <nav class="collapse navbar-collapse bs-navbar-collapse">
                
                <ul class="parent nav navbar-nav">
                    <li class="parent-item ">
                        <a href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_CONTACT ?>"><?php echo CONTACT ?></a>
                    </li>
                    <li class="parent-item ">
                        <a href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_DOCUMENT ?>">Công văn</a>
                    </li>
                    <li class="parent-item dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_SERVICE ?>">Dịch vụ <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo URL_APPLICATION ?>/bv/cung-cap-thiet-bi-1">Cung cấp thiết bị</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/bv/bao-tri-van-hanh-2">Bảo trì vận hành</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/bv/tu-van-thiet-ke-6">Tư vấn thiết kế</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/bv/cac-dich-vu-khac-7">Dịch vụ khác</a></li>
                        </ul>
                    </li>
                    <li class="parent-item dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_NEWS ?>"><?php echo NEWS?> <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_NEWS ?>/tin-noi-bo">Tin nội bộ</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_NEWS ?>/tin-lien-quan">Tin tức liên quan</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_NEWS ?>/tin-tuyen-dung">Tin tuyển dụng</a></li>
                        </ul>
                    </li>
                    <li class="parent-item ">
                        <a href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_MEMBERS ?>"><?php echo MEMBERS ?></a>
                        
                    </li>
                    <li class="parent-item dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="<?php echo URL_APPLICATION ?>/<?php echo URL_ALIAS_SHAREHOLDER ?>"><?php echo SHAREHOLDER ?> <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo URL_APPLICATION ?>/bv/thong-bao">Thông báo</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/bv/bao-cao-tai-chinh"">Báo cáo tài chính</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/bv/hoi-dong-co-dong"">Đại hội cổ đông</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/bv/thong-tin-co-phieu"">Thông tin về cổ phiếu</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/bv/bao-cao-thuong-nien"">Báo cáo thường niên</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/bv/bao-cao-hdqt"">Báo cáo HĐQT</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/bv/qui-che-quan-tri"">Qui chế quản trị</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/bv/ban-cao-bach"">Bản cáo bạch</a></li>
                            <li><a href="<?php echo URL_APPLICATION ?>/bv/dieu-le-to-chuc-hoat-dong"">Điều lệ tổ chức và hoạt động</a></li>
                        </ul>
                    </li>
                    <li class="parent-item ">
                        <a href="<?php echo URL_APPLICATION;?>/tinanh.php">Tin ảnh</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>