<?php
$ssFilter = $this->ssFilter;
$currentController = $this->layout()->controller;

$linkAdd = $this->cmsLinkAdmin(array('controller' => $currentController, 'action' => 'form'));
// DATA ITEM
$xhtmlItems = '';
if (!empty($this->items)) {
    foreach ($this->items as $item) {
        $class = $this->cycle(array('odd', 'even'))->next();
        $id = $item->id;
        $name = $item->name;
        $description = $item->description;
        $link = $item->link;
        $cid = $this->ocoderFormInput('cid[]', $id, array('type' => 'checkbox'));
        $linkEdit = $this->cmsLinkAdmin(array('controller' => $currentController, 'action' => 'form', 'id' => $id));
        $xhtmlItems .= '<tr class="' . $class . '">
                            <td>' . $cid . '</td>
                            <td style="text-align: left;">' . $name . '</td>
                            <td style="text-align: left;">' . $link . '</td>
                            <td>' . $id . '</td>
                            <td><a class="btn btn-default" href="' . $linkEdit . '"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>
                        </tr>';
    }
}
// LINK FORM SUBMIT
$linkFormSubmit = $this->cmsLinkAdmin(array('controller' => $currentController, 'action' => 'filter'));
?>
<section class="content-header">
    <h1>
        <?php echo BANNER_MANAGEMENT ?>
        <small><?php echo LISTS ?></small>
    </h1>
</section>
<!-- Main content -->
<section class="content">
    <!-- BUTTON -->
    <div class="row">
        <div class="text-center">
            <!--<a data-type="show-total" class="btn btn-app" href="#" onclick="javascript:changeOrdering();"><i class="fa fa-refresh"></i><?php echo UPDATE ?></a>--> 
            <a class="btn btn-app" href="<?php echo $linkAdd; ?>"><i class="fa fa-plus-square-o"></i> <?php echo ADD ?></a> 
<!--            <a data-type="show-total" class="btn btn-app" href="#" onclick="javascript:changemultiPublished(1);"><i class="fa fa-check-circle-o"></i> <?php echo ACTIVE ?></a>
            <a data-type="show-total" class="btn btn-app" href="#" onclick="javascript:changemultiPublished(0);"><i class="fa fa-circle-o"></i> <?php echo INACTIVE ?></a> -->
            <a data-type="show-total" class="btn btn-app" href="#" onclick="javascript:deleteItem('<?php echo CONFIRM_DELETE; ?>', '<?php echo NO_ITEMS_CHOOSE; ?>')"><i class="fa fa-minus-square-o"></i> <?php echo DELETE ?></a>
        </div>
    </div>
    <!-- NOTICE -->
    <?php 
    echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); 
    echo $this->flashMessenger()->render('error', array('alert', 'alert-danger')); 
    ?>
    <?php ?>
    <div class="box box-info">	
        <form name="adminForm" id="adminForm" action="<?php echo $linkFormSubmit; ?>" method="post">
            <div class="box-body table-responsive">
                <div class="dataTables_wrapper" role="grid">
                    <table class="table table-bordered table-striped dataTable text-center">
                        <!-- COLUMN TITLE -->
                        <thead>
                            <tr role="row">
                                <th class="col-sm-1"><input type="checkbox" id="check-all" /></th>
                                <th class="col-sm-5"><?php echo TITLE ?></th>
                                <th class="col-sm-4"><?php echo LINKS ?></th>
                                <th class="col-sm-1"><?php echo ID ?></th>
                                <th class="col-sm-1"><?php echo UPDATE ?></th>
                            </tr>
                        </thead>

                        <!-- CONTENT TABLE -->
                        <tbody><?php echo $xhtmlItems; ?></tbody>
                    </table>

                    <!-- PAGINATION -->
                    <?php
                    if(count($this->items) > 0){
                        $currentURL = $this->cmsLinkAdmin(array('controller' => $currentController, 'action' => 'index'));
                        echo $this->paginationControl($this->paginator, 'sliding', 'paginator.phtml', array('currentURL' => $currentURL));
                    }
                    ?>
                </div>
            </div>
            <!-- INPUT HIDDEN -->
            <?php //echo $strInputHidden; ?>
        </form>
    </div>
</section><!-- /.content -->