<?php
$urlCSS_DSDN = URL_TEMPLATE . '/frontend_dsdn/css';
$urlJS_DSDN = URL_TEMPLATE . '/frontend_dsdn/js';
$urlImage_DSDN = URL_TEMPLATE . '/frontend_dsdn/img';

use Zend\Session\Container;
$ssSystem = new Container('system');
?>

<div class="contact-content">
    <div class="container">
        <img src="<?php echo $urlImage_DSDN ?>/van-ban-phap-luat1.jpg" alt="hình nền">   
        <p class="contact_p">Công văn nội bộ</p>
        <div class="col-md-12">
            <div class="row col-md-7">
               
            </div>
        </div>
    </div>  
</div>
    
<div class="container page-home page-default">
    <div class="col-sm-12 page_content">
        <div class="breakum-line col-sm-12" id="cvan">
            <div class="col-sm-6">
               <a href="">Trang chủ</a>/<span> Công văn nội bộ</span> 
            </div>
           
            <div class="userinfo col-sm-6 pull-right">
                <p>Xin Chào,<span id="show_info"><?php echo $this->userLogged->fullname ?></span></p>
                
                <div class="box_info">
                    <div class="images">
                    <?php if ($userInfo->avatar!=null){?>
                       <img src="<?php echo URL_UPLOADS_AVATAR .'/'.$userInfo->avatar ?>" alt="" class="avatar"/> 
                       <?php }else {?>
                        <img src="<?php echo URL_UPLOADS_AVATAR .'/no_avatar.jpg' ?>" alt="" class="avatar"/> 
                        <?php }; ?>
                    </div>
                    <div class="box_foot">
                        <a href="<?php echo URL_APPLICATION . '/application/account/edit'?>" >Thông tin</a>
                        <a href="<?php echo URL_APPLICATION . '/application/account/logout' ?>" >Đăng xuất</a>
                    </div>
                    
                </div>
            </div>
        </div>
            
        
        <script>
            $(document).ready(function($) {
                
                $('#show_info').on('click',function(){
                    $('.box_info').toggle('blind', 200);

                });
            });
        </script>
        <div class="row block">
                    <div class="col-sm-12">
                        <a href="<?php echo URL_APPLICATION?>/cong-van/tai-len" class="btn btn_upload"> Tải công văn lên</a>
                    </div>
                </div>
        <div class="col-md-8 col-sm-12 document_new block">
             
            <p  class="title-document">Công văn mới nhất </span>
            <div class="wrap" >
                <?php foreach ($docArrCurrentMonth as $dateString => $docArrInDay) { ?>
                    <div class="bydate" id="<?php echo $dateString ?>">
                        <span><i class="fa fa-calendar"></i><?php echo $dateString ?></span>
                    </div>     
                    <!-- start of customer review box -->
                    <?php foreach ($docArrInDay as $document) { ?>
                    <div class="uc_customer_review_box">
                        <span class="uc_content" style="font-weight: bold;"><?php echo $document->name ?></span>
                        <span class="uc_content"><?php echo $document->description ?></span>
                        <div class="left-box ">
                            <p class="uc_name"><?php echo $this->userLogged->fullname ?></p>
                            <p class="uc_job"><?php echo $document->created ?></p>
                        </div>
                        <div class="right-box pull-right">
                            <!-- start of simple app download buttons -->
                            <div class="uc_simple_app_download_buttons">
                                <!--<a href="" class="uc_app_button">
                                    <i class="fa fa-download" aria-hidden="true"></i>
                                    <span class="uc_button_app">Tải xuống </span>
                                </a>-->
                                <a href="<?php echo URL_UPLOADS_DOCUMENTS . '/' . $document->link ?>" class="uc_app_button" target="_blank">
                                    <i class="fa fa-eye" aria-hidden="true"></i>
                                    <span class="uc_button_app">Xem chi tiết</span>
                                </a>
                            </div>
                        <!-- end of simple app download buttons -->
                        </div>
                        <?php if ($userInfo->avatar!=null){?>
                       <img  class="uc_avatar"src="<?php echo URL_UPLOADS_AVATAR .'/'.$userInfo->avatar ?>" alt="" class="avatar"/> 
                       <?php }else {?>
                        <img  class="uc_avatar"src="<?php echo URL_UPLOADS_AVATAR .'/no_avatar.jpg' ?>" alt="" class="avatar"/> 
                        <?php }; ?>
                    </div>
                    <?php } //end foreach ?>
                    <!-- end of customer review box --> 
                <?php }//end foreach ?>
            </div>
            <div class="colum-date">
                <?php foreach ($docArrCurrentMonth as $dateString => $docArrInDay) { ?>
                <a href="#<?php echo $dateString ?>"><?php echo date('d', strtotime($dateString));
                 ?></a>
                <?php }//end foreach ?>
            </div>
        </div>
       
        <div class="col-md-4 block col-sm-12 " id= "older_document">
            <div class="contact_info">
                <p class="title-document">Công văn cũ hơn</p>
                
                <!-- start of clean accordion -->
                <div class="uc_clean_accordion">
                    <div class="uc_clean_accordion_wrap">
                        <div id="accor-congvan" class="uc_clean_accorder_content">
                        <?php foreach ($docArrOld as $olderMonth=>$docOlder ){ ?>
                            <!-- start of line 1 -->
                            <h3 class="uc_head_line">
                               <a href="" class="uc_link_tittle">Công văn <?php echo $olderMonth ?></a>
                            </h3>
                            <div class="uc_line_content">
                            <?php foreach ($docOlder as $oderdocument ) { ?>
                               <p class="cv_p"><?php echo $oderdocument->name; ?><span></p>
                               <p class="cv_date"><?php echo $oderdocument->created; ?><a href="<?php echo URL_UPLOADS_DOCUMENTS . '/' . $document->link ?>" target="_blank"><i class="fa fa-download"></i></a></span></p>
                                
                             <?php } ?>   
                            </div>
                            <!-- end of line 1 -->
                            <?php } ?>
                            
                        </div>
                    </div>
                </div>
                <!-- end of clean accordion -->
            </div>
        </div>
        
    </div>        
</div>