<?php
$urlImage_DSDN = URL_TEMPLATE . '/frontend_dsdn/img';

use Zend\Session\Container;
$ssSystem = new Container('system');

$documents = $this->documents;
?>
<div class="contact-content">
    <div class="container contact-content">
        <img src="<?php echo $urlImage_DSDN ?>/van-ban-phap-luat1.jpg" alt="hình nền">   
        <p class="contact_p">Công văn nội bộ</p>
        <div class="col-md-12">
            <div class="row col-md-7">
               
            </div>
        </div>
    </div>  
</div>
    
<div class="container page-home page-default">
    <div class="col-sm-12 page_content">
        <div class="breakum-line">
            <a href="">Trang chủ</a>/<span> Công văn nội bộ</span>
        </div>
        <?php if($lastDocument){?>
            <div class="alert alert-success" role="alert">
                <span class="success"> Tải công văn thành công!</span>
            </div>
           <?php }?>
        <div class="col-md-7 col-sm-12 block">
            <form id="formUploadDoc" method="POST" enctype="multipart/form-data">
                <div class="row block">
                    <div class="col-sm-4">
                        <p class="formlabel">Tên Công văn :</p>
                    </div>
                    <div class="col-sm-8">
                        <input type="text" name="name" class="input_fname" id="docname"  />
                         <span id="nameErr" style="color:red"></span>
                    </div>
                </div>
                <div class="row block">
                    <div class="col-sm-4">
                        <p class="formlabel">Mô tả :</p>
                    </div>
                    <div class="col-sm-8">
                        <textarea name="description" id="docdes" ></textarea>
                        <span id="desErr" style="color:red"></span>
                    </div>
                </div>
                <div class="row block">
                    <div class="col-sm-4">
                        <p class="formlabel">File tải lên :</p>
                    </div>
                    <div class="group-button col-sm-8">
                        <input type="file" name="link" id="file"/>
                         <span id="fileErr" style="color:red"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                    </div>
                    <div class="group-button col-sm-8">
                        <button type="submit" class="btn btn-warning">Tải lên</button>
                    </div>
                </div>
                <!-- Hidden fields -->
                <input type="hidden" name="created_by" value="<?php echo $this->userLogged->id ?>"/>
            </form>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        
        $('#formUploadDoc').on ('submit',function(e) {
            var docname = $('#docname').val();
            var docdes = $('#docdes').val();
            var file = $('#file').val();
            if( docname == ''){
            e.preventDefault();
            $('#docname').addClass('has-err');
            $('#nameErr').text('* Vui lòng nhập tên công văn');
            
           } else {
            if( docdes == ''){
            e.preventDefault();
            $('#docdes').addClass('has-err');
            $('#desErr').text('* Không để trống mô tả');  
               
           }else {
                if (file == ''){
                    e.preventDefault();
                 $('#fileErr').text('* vui lòng chọn file');  
                }
            }
        }
        form.submit();
        });
    });
</script>