
<div class="container" style="margin-bottom:10px">
	<div class="mail-box row">
      <aside class="sm-side">
          <div class="user-head">
              <a class="inbox-avatar" href="javascript:;">
                  <img  width="64" hieght="60" src="http://bootsnipp.com/img/avatars/ebeb306fd7ec11ab68cbcaa34282158bd80361a7.jpg">
              </a>
              <div class="user-name">
                  <h5><a href="#">Alireza Zare</a></h5>
                  <span><a href="#">Info.Ali.Pci@Gmail.com</a></span>
              </div>
              <a class="mail-dropdown pull-right" href="">
                  <i class="fa fa-sign-out"></i>
              </a>
          </div>
          <div class="inbox-body">
              <a href="#myModal" data-toggle="modal"  title="Compose"    class="btn btn-compose">
                  Soạn mới
              </a>
              <!-- Modal -->
              <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal" class="modal fade" style="display: none;">
                  <div class="modal-dialog">
                      <div class="modal-content">
                          <div class="modal-header">
                              <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                              <h4 class="modal-title">Soạn mới</h4>
                          </div>
                          <div class="modal-body">
                              <form role="form" class="form-horizontal">
                                  <div class="form-group">
                                      <label class="col-lg-2 control-label">To</label>
                                      <div class="col-lg-10">
                                          <input type="text" placeholder="" id="inputEmail1" class="form-control">
                                      </div>
                                  </div>
                                  <div class="form-group">
                                      <label class="col-lg-2 control-label">Cc / Bcc</label>
                                      <div class="col-lg-10">
                                          <input type="text" placeholder="" id="cc" class="form-control">
                                      </div>
                                  </div>
                                  <div class="form-group">
                                      <label class="col-lg-2 control-label">Subject</label>
                                      <div class="col-lg-10">
                                          <input type="text" placeholder="" id="inputPassword1" class="form-control">
                                      </div>
                                  </div>
                                  <div class="form-group">
                                      <label class="col-lg-2 control-label">Message</label>
                                      <div class="col-lg-10">
                                          <textarea rows="10" cols="30" class="form-control" id="" name=""></textarea>
                                      </div>
                                  </div>

                                  <div class="form-group">
                                      <div class="col-lg-offset-2 col-lg-10">
                                          <span class="btn green fileinput-button">
                                            <i class="fa fa-plus fa fa-white"></i>
                                            <span>Attachment</span>
                                            <input type="file" name="files[]" multiple="">
                                          </span>
                                          <button class="btn btn-send" type="submit">Send</button>
                                      </div>
                                  </div>
                              </form>
                          </div>
                      </div><!-- /.modal-content -->
                  </div><!-- /.modal-dialog -->
              </div><!-- /.modal -->
          </div>
          <ul class="inbox-sidebar inbox-divider nav nav-tabs">
              <li class="active">
                  <a href="#tab-1" data-toggle="tab"><i class="fa fa-inbox"></i> Công văn Đến <span class="label label-danger pull-right">2</span></a>

              </li>
              <li>
                  <a href="#tab-2" data-toggle="tab"><i class="fa fa-envelope-o"></i> Công văn đã gửi</a>
              </li>
              <li>
                  <a href="#tab-3" data-toggle="tab"><i class="fa fa-bookmark-o"></i> Công văn quan trọng</a>
              </li>
              <li>
                  <a href="#tab-4" data-toggle="tab"><i class=" fa fa-external-link"></i> Công văn chưa đọc <span class="label label-info pull-right">30</span></a>
              </li>
              <li>
                  <a href="#tab-5" data-toggle="tab"><i class=" fa fa-trash-o"></i> Công văn đã xóa</a>
              </li>
          </ul>
          <ul class="nav nav-pills nav-stacked labels-info inbox-divider">
              <li> <h4>Labels</h4> </li>
              <li> <a href="#"> <i class=" fa fa-sign-blank text-danger"></i> Work </a> </li>
              <li> <a href="#"> <i class=" fa fa-sign-blank text-success"></i> Design </a> </li>
              <li> <a href="#"> <i class=" fa fa-sign-blank text-info "></i> Family </a>
              </li><li> <a href="#"> <i class=" fa fa-sign-blank text-warning "></i> Friends </a>
              </li><li> <a href="#"> <i class=" fa fa-sign-blank text-primary "></i> Office </a>
              </li>
          </ul>
          <ul class="nav nav-pills nav-stacked labels-info ">
              <li> <h4>Buddy online</h4> </li>
              <li> <a href="#"> <i class=" fa fa-circle text-success"></i>Alireza Zare <p>I do not think</p></a>  </li>
              <li> <a href="#"> <i class=" fa fa-circle text-danger"></i>Dark Coders<p>Busy with coding</p></a> </li>
              <li> <a href="#"> <i class=" fa fa-circle text-muted "></i>Mentaalist <p>I out of control</p></a>
              </li><li> <a href="#"> <i class=" fa fa-circle text-muted "></i>H3s4m<p>I am not here</p></a>
              </li><li> <a href="#"> <i class=" fa fa-circle text-muted "></i>Dead man<p>I do not think</p></a>
              </li>
          </ul>

          <div class="inbox-body text-center">
              <div class="btn-group">
                  <a class="btn mini btn-primary" href="javascript:;">
                      <i class="fa fa-plus"></i>
                  </a>
              </div>
              <div class="btn-group">
                  <a class="btn mini btn-success" href="javascript:;">
                      <i class="fa fa-phone"></i>
                  </a>
              </div>
              <div class="btn-group">
                  <a class="btn mini btn-info" href="javascript:;">
                      <i class="fa fa-cog"></i>
                  </a>
              </div>
          </div>

      </aside>
      <aside class="lg-side tab-content">
      	<div class="tab-pane fade active in" id="tab-1">
	          <div class="inbox-head">
	              <h3>Công văn Đến</h3>
	          </div>
	          <div class="inbox-body">
	            <table id="example" class="table hover" cellspacing="0" width="100%">
			        <thead>
			            <tr>
			                <th>Công văn Từ</th>
			                <th>Tiêu đề</th>
			                <th>Phòng ban</th>
			                <th>Age</th>
			                <th>Ngày gửi</th>
			                <th>Salary</th>
			            </tr>
			        </thead>
			        <tfoot>
			            <tr>
			                <th>Name</th>
			                <th>Position</th>
			                <th>Office</th>
			                <th>Age</th>
			                <th>Start date</th>
			                <th>Salary</th>
			            </tr>
			        </tfoot>
			        <tbody>
			            <tr>
			                <td>Tiger Nixon</td>
			                <td>System Architect</td>
			                <td>Edinburgh</td>
			                <td>61</td>
			                <td>2011/04/25</td>
			                <td>$320,800</td>
			            </tr>
			            <tr>
			                <td>Garrett Winters</td>
			                <td>Accountant</td>
			                <td>Tokyo</td>
			                <td>63</td>
			                <td>2011/07/25</td>
			                <td>$170,750</td>
			            </tr>
			            <tr>
			                <td>Ashton Cox</td>
			                <td>Junior Technical Author</td>
			                <td>San Francisco</td>
			                <td>66</td>
			                <td>2009/01/12</td>
			                <td>$86,000</td>
			            </tr>
			            <tr>
			                <td>Cedric Kelly</td>
			                <td>Senior Javascript Developer</td>
			                <td>Edinburgh</td>
			                <td>22</td>
			                <td>2012/03/29</td>
			                <td>$433,060</td>
			            </tr>
			            <tr>
			                <td>Airi Satou</td>
			                <td>Accountant</td>
			                <td>Tokyo</td>
			                <td>33</td>
			                <td>2008/11/28</td>
			                <td>$162,700</td>
			            </tr>
			            <tr>
			                <td>Brielle Williamson</td>
			                <td>Integration Specialist</td>
			                <td>New York</td>
			                <td>61</td>
			                <td>2012/12/02</td>
			                <td>$372,000</td>
			            </tr>
			            <tr>
			                <td>Herrod Chandler</td>
			                <td>Sales Assistant</td>
			                <td>San Francisco</td>
			                <td>59</td>
			                <td>2012/08/06</td>
			                <td>$137,500</td>
			            </tr>
			            <tr>
			                <td>Rhona Davidson</td>
			                <td>Integration Specialist</td>
			                <td>Tokyo</td>
			                <td>55</td>
			                <td>2010/10/14</td>
			                <td>$327,900</td>
			            </tr>
			            <tr>
			                <td>Donna Snider</td>
			                <td>Customer Support</td>
			                <td>New York</td>
			                <td>27</td>
			                <td>2011/01/25</td>
			                <td>$112,000</td>
			            </tr>
			            <tr>
			                <td>Tiger Nixon</td>
			                <td>System Architect</td>
			                <td>Edinburgh</td>
			                <td>61</td>
			                <td>2011/04/25</td>
			                <td>$320,800</td>
			            </tr>
			            <tr>
			                <td>Garrett Winters</td>
			                <td>Accountant</td>
			                <td>Tokyo</td>
			                <td>63</td>
			                <td>2011/07/25</td>
			                <td>$170,750</td>
			            </tr>
			            <tr>
			                <td>Ashton Cox</td>
			                <td>Junior Technical Author</td>
			                <td>San Francisco</td>
			                <td>66</td>
			                <td>2009/01/12</td>
			                <td>$86,000</td>
			            </tr>
			            <tr>
			                <td>Cedric Kelly</td>
			                <td>Senior Javascript Developer</td>
			                <td>Edinburgh</td>
			                <td>22</td>
			                <td>2012/03/29</td>
			                <td>$433,060</td>
			            </tr>
			            <tr>
			                <td>Airi Satou</td>
			                <td>Accountant</td>
			                <td>Tokyo</td>
			                <td>33</td>
			                <td>2008/11/28</td>
			                <td>$162,700</td>
			            </tr>
			            <tr>
			                <td>Brielle Williamson</td>
			                <td>Integration Specialist</td>
			                <td>New York</td>
			                <td>61</td>
			                <td>2012/12/02</td>
			                <td>$372,000</td>
			            </tr>
			            <tr>
			                <td>Herrod Chandler</td>
			                <td>Sales Assistant</td>
			                <td>San Francisco</td>
			                <td>59</td>
			                <td>2012/08/06</td>
			                <td>$137,500</td>
			            </tr>
			            <tr>
			                <td>Rhona Davidson</td>
			                <td>Integration Specialist</td>
			                <td>Tokyo</td>
			                <td>55</td>
			                <td>2010/10/14</td>
			                <td>$327,900</td>
			            </tr>
			            <tr>
			                <td>Donna Snider</td>
			                <td>Customer Support</td>
			                <td>New York</td>
			                <td>27</td>
			                <td>2011/01/25</td>
			                <td>$112,000</td>
			            </tr>
			        </tbody>
			    </table>
	          </div>
          </div>
          <div class="tab-pane fade" id="tab-2">
	          <div class="inbox-head">
	              <h3> Công văn đã gửi</h3>
	          </div>
	      </div>
	      <div class="tab-pane fade" id="tab-3">
	          <div class="inbox-head">
	              <h3> Công văn quan trọng</h3>
	          </div>
	      </div>
	      <div class="tab-pane fade" id="tab-4">
	          <div class="inbox-head">
	              <h3>  Công văn chưa đọc </h3>
	          </div>
	      </div>
	      <div class="tab-pane fade" id="tab-5">
	          <div class="inbox-head">
	              <h3> Công văn đã xóa</h3>
	          </div>
	      </div>
      </aside>
      
  </div>
</div>