<?php
$urlCSS = URL_TEMPLATE . '/frontend/css';
$urlJS = URL_TEMPLATE . '/frontend/js';
$urlImage = URL_TEMPLATE . '/frontend/images';
?>

<?php echo $this->doctype(); ?>
<html>
    <head>
        <?php
        echo $this->headTitle();
        echo //$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')
//                $this->headMeta()->appendName('description', PAGE_TITLE)
                 $this->headMeta()->setCharset('utf-8');

        echo $this->headLink()->appendStylesheet(array(
                    'rel' => 'shortcut icon',
                    'type' => 'image/x-icon',
                    'href' => $urlImage . '/favicon.ico'
                        ), 'PREPEND')
                ->appendStylesheet(URL_PUBLIC . '/css/bootstrap.min.css')
        // ->appendStylesheet($urlCSS . '/styles.less')
        ;

        echo '<link href="' . $urlCSS . '/style.less" rel="stylesheet/less">';

        echo $this->headScript()->appendFile($urlJS . '/jquery-1.11.2.min.js')
                ->appendFile($urlJS . '/bootstrap.min.js')
                ->appendFile($urlJS . '/less.min.js');
        ?>	

        <style type="text/css">
            <!--
            #slideCont {
                /*border:solid 1px #000;*/
                text-align:center;
            }

            #slideCont img {
                margin: 5px;
            }
            -->
        </style>

        
    </head>
    <body>
        <?php //echo $this->blkConfigs() ?>
        <div class="body-wrapper container">
            <!-- Header of Website -->
            <header class="navbar navbar-static-top bs-docs-nav" id="top" role="banner">
                <?php include_once 'includes/header.phtml'; ?>
            </header> <!-- End Header of Website -->

            <?php echo $this->content; ?>

            <?php include_once 'includes/footer.phtml'; ?>
        </div>
    </body>
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-59438542-1', 'auto');
    ga('send', 'pageview');
    </script>
</html>