<?php
$urlCSS_DSDN = URL_TEMPLATE . '/frontend_dsdn/css';
$urlJS_DSDN = URL_TEMPLATE . '/frontend_dsdn/js';
$urlImage_DSDN = URL_TEMPLATE . '/frontend_dsdn/img';

use Zend\Session\Container;

$ssSystem = new Container('system');
$helperString = new \Ocoder\Helper\String;

?>

<div class="container contact-content" style="padding: 0">
        <img src="<?php echo $urlImage_DSDN?>/news.jpg" alt="">   
        <p class="contact_p">Quan Hệ Cổ Đông</p>
    </div>
    <div class="page-default ">
        <div class="container content">
            <div class="breakum-line">
                <a href="">Trang chủ</a>/<span> Quan Hệ Cổ Đông </span>
            </div>
        
            <div class="col-md-8 col-sm-12 block">
                <div class="news">
                    <a href="">Xí nghiệp TTTH ĐS Bình Trị Thiên</a>
                    <hr>
                    <div class="new_box">
                        
                        <div class="under_new_content">
                            <a href="#">Tin tức của đơn vị thành viên</a>
                            <a href="#">Tin tức của đơn vị thành viên</a>
                            <a href="#">Tin tức của đơn vị thành viên</a>
                            <a href="#">Tin tức của đơn vị thành viên</a>
                            <a href="#">Tin tức của đơn vị thành viên</a>
                            <a href="#">Tin tức của đơn vị thành viên</a>
                        </div>
                        <div class="link"><a href="" class="linkmore">Xem thêm </a></div>
                        
                    </div>
                </div>
                
            </div>
            <div class="col-md-4 col-sm-12 block ">
                <div class="search padding_right5">
                    <input type="text" class="form-control input-search" maxlength="64" placeholder="Tìm kiếm" />
                    <button type="submit" class="btn btn-primary btn-search"><i class="fa fa-search"></i><p>Tìm kiếm</p></button>
                </div>
           
            
                <div class="tinanh block">
                    <span class="tittle">Tin ảnh</span>
                    <div class="items">
                    <a href=""><img src="<?php echo $urlImage_DSDN?>/tinanh/tin_anh1_.jpg" alt="thumbnail" title="Hoạt động công ty" class="img"></a><a href="#" title="Hoạt động công ty" class="newslink">Đà Nẵng: Sẽ sớm di dời ga đường sắt ra khỏi nội thành</a><br>
                    <span class="info">32 photos | 26639 view</span>
                    </div>
                    <div class="items">
                    <a href=""><img src="<?php echo $urlImage_DSDN?>/tinanh/tin_anh2_.jpg" alt="thumbnail" title="Hoạt động công ty" class="img"></a><a href="#" title="Hoạt động công ty" class="newslink">Triển lãm công nghệ khai khoáng</a><br>
                    <span class="info">32 photos | 26639 view</span>
                    </div>
                    <div class="items">
                    <a href=""><img src="<?php echo $urlImage_DSDN?>/tinanh/tin_anh3_.jpg" alt="thumbnail" title="Hoạt động công ty" class="img"></a>
                    <a href="#" title="Hoạt động công ty" class="newslink">Ga đường sắt mới sẽ được đặt tại quận Liên Chiểu</a>
                    <span class="info">32 photos | 26639 view</span>
                    </div>
                    <div class="items">
                    <a href=""><img src="<?php echo $urlImage_DSDN?>/tinanh/post1.jpg" alt="thumbnail" title="Hoạt động công ty" class="img"></a><a href="#" title="Hoạt động công ty" class="newslink">Phương án di dời và xây dựng ga đường sắt Đà Nẵng</a><br>
                    <span class="info">32 photos | 26639 view</span>
                    </div>
                    <div class="items">
                    <a href=""><img src="<?php echo $urlImage_DSDN?>/tinanh/tin_anh2_.jpg" alt="thumbnail" title="Hoạt động công ty" class="img"></a><a href="#" title="Hoạt động công ty" class="newslink">Triển lãm công nghệ khai khoáng</a><br>
                    <span class="info">32 photos | 26639 view</span>
                    </div>

                    <div class="link"><a href="" class="linkmore">Xem thêm </a></div>
                </div>
           
            
                <div class="otherlink block">
                    <span>video</span>
                    <iframe width="100%" height="315" src="https://www.youtube.com/embed/ahLjVibR6oY" frameborder="0" allowfullscreen></iframe>
                </div>
            
            
                 
                <div class="tinanh block">
                    <span class="tittle">Tin Thể thao</span>
                    <div class="items">
                    <a href=""><img src="<?php echo $urlImage_DSDN?>/tinanh/tin_anh1_.jpg" alt="thumbnail" title="Hoạt động công ty" class="img"></a><a href="#" title="Hoạt động công ty" class="newslink">Đà Nẵng: Sẽ sớm di dời ga đường sắt ra khỏi nội thành</a><br>
                    <span class="info">32 photos | 26639 view</span>
                    </div>
                    <div class="items">
                    <a href=""><img src="<?php echo $urlImage_DSDN?>/tinanh/tin_anh2_.jpg" alt="thumbnail" title="Hoạt động công ty" class="img"></a><a href="#" title="Hoạt động công ty" class="newslink">Triển lãm công nghệ khai khoáng</a><br>
                    <span class="info">32 photos | 26639 view</span>
                    </div>
                    <div class="items">
                    <a href=""><img src="<?php echo $urlImage_DSDN?>/tinanh/tin_anh3_.jpg" alt="thumbnail" title="Hoạt động công ty" class="img"></a>
                    <a href="#" title="Hoạt động công ty" class="newslink">Ga đường sắt mới sẽ được đặt tại quận Liên Chiểu</a>
                    <span class="info">32 photos | 26639 view</span>
                    </div>
                    <div class="items">
                    <a href=""><img src="<?php echo $urlImage_DSDN?>/tinanh/post1.jpg" alt="thumbnail" title="Hoạt động công ty" class="img"></a><a href="#" title="Hoạt động công ty" class="newslink">Phương án di dời và xây dựng ga đường sắt Đà Nẵng</a><br>
                    <span class="info">32 photos | 26639 view</span>
                    </div>
                    <div class="items">
                    <a href=""><img src="<?php echo $urlImage_DSDN ?>/tinanh/tin_anh2_.jpg" alt="thumbnail" title="Hoạt động công ty" class="img"></a><a href="#" title="Hoạt động công ty" class="newslink">Triển lãm công nghệ khai khoáng</a><br>
                    <span class="info">32 photos | 26639 view</span>
                    </div>
                    <div class="link"><a href="" class="linkmore">Xem thêm </a></div>
                </div>
          
            
        </div>
    </div> 