<?php
$urlCSS_DSDN = URL_TEMPLATE . '/frontend_dsdn/css';
$urlJS_DSDN = URL_TEMPLATE . '/frontend_dsdn/js';
$urlImage_DSDN = URL_TEMPLATE . '/frontend_dsdn/img';

use Zend\Session\Container;

$ssSystem = new Container('system');
$helperString = new \Ocoder\Helper\String;

?>

<div class="container contact-content" style="padding: 0">
    <img src="<?php echo $urlImage_DSDN?>/news.jpg" alt="">   
    <p class="contact_p">Quan Hệ Cổ Đông</p>
</div>
    <div class="page-default ">
        <div class="container content">
            <div class="breakum-line">
                <a href="">Trang chủ</a>/<span> Quan Hệ Cổ Đông </span>
            </div>
        
            <div class="col-md-8 col-sm-12 block">
                <div class="news">
                    <a href="">Xí nghiệp TTTH ĐS Bình Trị Thiên</a>
                    <hr>
                    <div class="new_box">
                        
                        <div class="under_new_content">
                            <a href="#">Tin tức của đơn vị thành viên</a>
                            <a href="#">Tin tức của đơn vị thành viên</a>
                            <a href="#">Tin tức của đơn vị thành viên</a>
                            <a href="#">Tin tức của đơn vị thành viên</a>
                            <a href="#">Tin tức của đơn vị thành viên</a>
                            <a href="#">Tin tức của đơn vị thành viên</a>
                        </div>
                        <div class="link"><a href="" class="linkmore">Xem thêm </a></div>
                        
                    </div>
                </div>
                
            </div>
            <div class="col-md-4 col-sm-12 block ">
                <div class="search padding_right5 block">
                    <form action="<?php echo URL_APPLICATION . '/tim-kiem/' ?>" method="GET">
                        <input type="text" class="form-control input-search" id="keyword-search" maxlength="64" name='tk' placeholder="<?php echo SEARCH ?>" value="<?php echo array_key_exists('tk', $_GET) ? $_GET['tk'] : '' ?>" />
                        <button type="submit" class="btn btn-primary btn-search"><i class="fa fa-search"></i><p><?php echo SEARCH ?></p></button>
                    </form>
                </div>

                <div class="block">
                    <?php $this->blkLatestNews(); ?>
                </div>
           
            
                <div class="block">
                    <?php $this->blkVideo();?>
                </div>
            </div>
        </div>
    </div> 