<?php

use Zend\Json\Json;

$ssFilter = $this->ssFilter;
$currentController = $this->layout()->controller;

// CREATE INPUT HIDDEN
$inputHiddenOrder = $this->ocoderFormHidden('order', $ssFilter['order']);
$inputHiddenOrderBy = $this->ocoderFormHidden('order_by', $ssFilter['order_by']);
$inputStatusID = $this->ocoderFormHidden('status_id', null);
$inputStatusValue = $this->ocoderFormHidden('status_value', null);

$strInputHidden = $inputHiddenOrder . $inputHiddenOrderBy . $inputStatusID . $inputStatusValue;

// CREATE SELECTBOX
//$arrKeywordType = array('name' => 'Search by NAME', 'id' => 'Search by ID', 'all' => 'Search by ALL');
//$slbKeywordType = $this->ocoderFormSelect('filter_keyword_type', null, $arrKeywordType, $ssFilter['filter_keyword_type']);
//$slbFilterStatus = $this->ocoderFormSelect('filter_status', '-- Select a status --', array('active' => 'Active', 'inactive' => 'Inactive'), $ssFilter['filter_status']);
//$slbFilterSpecial = $this->ocoderFormSelect('filter_special', '-- Select a type --', array('yes' => 'Special', 'no' => 'Normal'), $ssFilter['filter_special']);
//$slbFilterCategory = $this->ocoderFormSelect('filter_category', '-- Select a category --', $this->slbCategory, $ssFilter['filter_category']);
// CREATE INPUT
$inputKeyword = $this->ocoderFormInput('filter_keyword_value', $ssFilter['filter_keyword_value'], array('class' => 'form-control input-sm'));

// CREATE BUTTON
$btnClear = $this->ocoderFormButton('btn-clear', 'btn-clear', 'Clear', array('class' => 'btn-default'));
$btnSearch = $this->ocoderFormButton('btn-go', 'btn-go', 'Search!', array('class' => 'btn-primary'));

// DATA ITEM
$xhtmlItems = '';
if (!empty($this->items)) {
    foreach ($this->items as $item) {

        $class = $this->cycle(array('odd', 'even'))->next();
        $id = $item->id;
        $name = $item->name;

        // Picture
        $picture = $item->picture;
        $pictureURL = URL_FILES . '/books/thumb/no-avatar.png';
        if (!empty($picture)) {
            $pictureURL = URL_FILES . '/books/thumb/80x120/' . $picture;
        }

        $price = $item->price;

        $created = date('d-m-Y', strtotime($item->created));
        $createdBy = $item->created_by;
        $modified = date('d-m-Y', strtotime($item->modified));
        $modifiedBy = $item->modified_by;
        $catName = $item->category_name;

        $status = $this->cmsButtonPublished($id, $item->status);
        $special = $this->cmsButtonSpecial($id, $item->special);

        $ordering = $this->ocoderFormInput('ordering[' . $id . ']', $item->ordering, array('class' => 'input-ordering'));
        $cid = $this->ocoderFormInput('cid[]', $id, array('type' => 'checkbox'));
        $linkEdit = $this->cmsLinkAdmin(array('controller' => $currentController, 'action' => 'form', 'id' => $id));
        $xhtmlItems .= '<tr class="' . $class . '">
								<td>' . $cid . '</td>
								<td style="text-align: left;"><a href="' . $linkEdit . '">' . $name . '</a></td>
								<td>' . $price . '</td>
								<td>' . $special . '</td>
								<td>' . $status . '</td>
								<td>' . $id . '</td>
                                                                <td><a class="btn btn-default" href="' . $linkEdit . '"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>
							</tr>';
    }
}
// LINK FORM SUBMIT
$linkFormSubmit = $this->cmsLinkAdmin(array('controller' => $currentController, 'action' => 'filter'));
?>

<!-- BUTTON -->
<?php echo $this->render('area_toolbar.phtml'); ?>

<!-- NOTICE -->
<?php echo $this->flashMessenger()->render(); ?>

<div class="box box-info">
    <form name="adminForm" id="adminForm"
          action="<?php echo $linkFormSubmit; ?>" method="post">
        <!--         FILTER 
                <div class="box-header" style="padding-top: 10px;">
                     FILTER KEYWORD 
                    <div class="col-xs-4">
        <?php
        echo $this->partial('area_search.phtml', array('slbKeywordType' => $slbKeywordType, 'inputKeyword' => $inputKeyword, 'strButton' => $btnClear . $btnSearch));
        ?>
                    </div>
                     FILTER STATUS 
                    <div class="col-xs-8">
                        <div class="dataTables_filter pull-right">
        <?php echo $slbFilterSpecial . ' ' . $slbFilterCategory . ' ' . $slbFilterStatus; ?>
                        </div>
                    </div>
                </div>-->

        <div class="box-body table-responsive">
            <div class="dataTables_wrapper" role="grid">
                <table
                    class="table table-bordered table-striped dataTable text-center">
                    <!-- COLUMN TITLE -->
                    <thead>
                        <tr role="row">
                            <th class="col-sm-1"><input type="checkbox" id="check-all" /></th>
                            <th class="col-sm-6"><?php echo NAME ?></th>
                            <th class="col-sm-1"><?php echo PRICE ?></th>
                            <th class="col-sm-1"><?php echo SPECIAL ?></th>
                            <th class="col-sm-1"><?php echo PUBLISHED ?></th>
                            <th class="col-sm-1"><?php echo ID ?></th>
                            <th class="col-sm-1"><?php echo EDIT ?></th>
                                <?php
//                                echo $this->cmsLinkSort('Name', 'name', $ssFilter, array('style' => 'width:20%'));
//                                echo $this->cmsLinkSort('Price', 'price', $ssFilter);
//                                echo $this->cmsLinkSort('Special', 'special', $ssFilter, array('style' => 'width:8%'));
//                                echo $this->cmsLinkSort('Status', 'status', $ssFilter, array('style' => 'width:7%'));
//                                echo $this->cmsLinkSort('ID', 'id', $ssFilter, array('style' => 'width:5%'));
                                ?>
                        </tr>
                    </thead>

                    <!-- CONTENT TABLE -->
                    <tbody><?php echo $xhtmlItems; ?></tbody>
                </table>

                <!-- PAGINATION -->
                <?php
                $currentURL = $this->cmsLinkAdmin(array('controller' => $currentController, 'action' => 'index'));
                echo $this->paginationControl($this->paginator, 'sliding', 'paginator.phtml', array('currentURL' => $currentURL));
                ?>
            </div>
        </div>
        <!-- INPUT HIDDEN -->
        <?php echo $strInputHidden; ?>
    </form>
</div>
