<?php
$urlCSS_DSDN = URL_TEMPLATE . '/frontend_dsdn/css';
$urlJS_DSDN = URL_TEMPLATE . '/frontend_dsdn/js';
$urlImage_DSDN = URL_TEMPLATE . '/frontend_dsdn/img';

use Zend\Session\Container;
$ssSystem = new Container('system');



?>

<div class="contact-content">
        <div class="container">
            <img src="<?php echo $urlImage_DSDN;?>/contact-img.jpg" alt="">   
            <p class="contact_p">Thông tin liên hệ</p>
            <div class="col-md-12">
                
                <div class="row col-md-7">
                    
                </div>
            </div>
        </div>  
    </div>
    
        
 
    <div class="container page-home page-default">
        
            <div class="col-sm-12 page_content">
                <div class="breakum-line">
                    <a href="<?php echo URL_APPLICATION ?>"><?php echo HOME; ?></a>/<span> Thông tin liên hệ</span>
                </div>
                <div class="col-sm-12 col-md-7">
                    <p  class="title-default">Liên hệ và Góp ý </p>
                    <form id="contactform" class="contactform" method="POST">
                        <div class="form-group col-sm-6">
                            <label for="contactInputName">Họ và tên:</label>
                            <input type="text" class="input_fname" name="full_name" id="contactInputName" required>

                        </div>
                        <div class="form-group col-sm-6">
                            <label for="contactInputemail">Email :</label>
                            <input type="email" class="input_email has-err" name="email" id="contactInputemail" required>
                        </div>
                        <div class="form-group col-sm-12">
                            <label for="contactInputerea">Nội dung</label>
                            <textarea class="input_textearea" id="contactInputerea" name="comment" rows="3" required></textarea>
                        </div>
                        <div class="form-group col-sm-12 text-left">
                            <span class="show_err"></span>
                        </div>
                        <div class="form-group col-sm-12 text-center">
                            <button type="submit" id="send_contact" class="btn btn-primary">Gửi đi</button>
                        </div>
                    </form>
                </div>
               
                <div class="col-md-5 col-sm-12 block">
                    <div class="contact_info">
                        <p  class="title-default">Thông tin liên hệ </p>
                        <p class="comname"><?php echo $ssSystem->configs->company_name?></p>
                        <p>Địa chỉ: <span><?php echo $ssSystem->configs->company_address?></span></p>
                        <p>Số điện thoại:<a href="tel:<?php echo $ssSystem->configs->company_phone?>" class="pull-right"><?php echo $ssSystem->configs->company_phone?></a></p>
                        <p>Fax :<a href="" class="pull-right"><?php echo $ssSystem->configs->company_fax?></a></p>
                        <p>Email:<a href="mailto:<?php echo $ssSystem->configs->company_email?>" class="pull-right"><?php echo $ssSystem->configs->company_email?></a></p>
                    </div>
                </div>
                <div class="col-sm-12">
                    <div style="overflow:hidden;width:100%;height:500px;resize:none;max-width:100%;margin-bottom:30px"><div id="gmap-display" style="height:100%; width:100%;max-width:100%;"><iframe style="height:100%;width:100%;border:0;" frameborder="0" src="https://www.google.com/maps/embed/v1/place?q=<?php echo $ssSystem->configs->company_name?>&key=AIzaSyAN0om9mFmy1QN6Wf54tXAowK4eT0ZUPrU&zoom=19"></iframe></div><a class="embedded-map-code" href="https://www.hostingreviews.website" id="make-map-data">Read more</a><style>#gmap-display .map-generator{width: 100%; max-height: 100%; background: none;</style></div><script src="https://www.hostingreviews.website/google-maps-authorization.js?id=028e13ce-d080-2b9e-3972-68fa5fda02ba&c=embedded-map-code&u=1465462995" defer="defer" async="async"></script>
                </div>
            </div>
        
    </div>
    <script>
    $(document).ready(function() {

});
        
    </script>