<?php
$urlCSS_DSDN = URL_TEMPLATE . '/frontend_dsdn/css';
$urlJS_DSDN = URL_TEMPLATE . '/frontend_dsdn/js';
$urlImage_DSDN = URL_TEMPLATE . '/frontend_dsdn/img';

use Zend\Session\Container;
$ssSystem = new Container('system');
?>
<div class="contact-content">
        <div class="container">
            <img src="img/van-ban-phap-luat1.jpg" alt="hình nền">   
            <p class="contact_p">Công văn nội bộ</p>
            <div class="col-md-12">
                
                <div class="row col-md-7">
                   
                </div>
            </div>
        </div>  
    </div>
    
        
 
    <div class="container page-home page-default">
        
            <div class="col-sm-12 page_content">
                <div class="breakum-line">
                    <a href="">Trang chủ</a>/<span> Công văn nội bộ</span>
                </div>
                <div class="col-md-7 col-sm-12">
                    <span  class="title-default">Công văn mới nhất </span>
                    <div class="wrap"  style="max-height: 535px; overflow: scroll;">
                        <!-- start of customer review box -->
                        <div class="uc_customer_review_box">
                            <span class="uc_content">In sit cras, vel auctor eu augue! Ut, nec vel adipiscing? Amet pulvinar, nascetur sed vut nunc! Scelerisque mus in. Enim, nec penatibus augue, et arcu! Cursus odio! Montes porttitor lectus!</span>
                            <div class="left-box ">

                                <p class="uc_name">Rafael Oliveira</p>
                                <p class="uc_job">CEO - Rafael Oliveira Design</p>
                            </div>
                            <div class="right-box pull-right">
                                <!-- start of simple app download buttons -->
                                <div class="uc_simple_app_download_buttons">
                                    <a href="" class="uc_app_button">
                                        <i class="fa fa-download" aria-hidden="true"></i>
                                        <span class="uc_button_app">Tải xuống </span>
                                    </a>
                                    <a href="" class="uc_app_button">
                                        <i class="fa fa-eye" aria-hidden="true"></i>
                                        <span class="uc_button_app">Xem nhanh</span>
                                    </a>
                                </div>
                            <!-- end of simple app download buttons -->
                            </div>
                            <img class="uc_avatar" src="img/icon-human/1.jpg" alt="avatar"/>
                        </div>
                        <!-- end of customer review box --> 
                        <!-- start of customer review box -->
                        <div class="uc_customer_review_box">
                            <span class="uc_content">In sit cras, vel auctor eu augue! Ut, nec vel adipiscing? Amet pulvinar, nascetur sed vut nunc! Scelerisque mus in. Enim, nec penatibus augue, et arcu! Cursus odio! Montes porttitor lectus!</span>
                            <div class="left-box ">

                                <p class="uc_name">Rafael Oliveira</p>
                                <p class="uc_job">CEO - Rafael Oliveira Design</p>
                            </div>
                            <div class="right-box pull-right">
                                <!-- start of simple app download buttons -->
                                <div class="uc_simple_app_download_buttons">
                                    <a href="" class="uc_app_button">
                                        <i class="fa fa-download" aria-hidden="true"></i>
                                        <span class="uc_button_app">Tải xuống </span>
                                    </a>
                                    <a href="" class="uc_app_button">
                                        <i class="fa fa-eye" aria-hidden="true"></i>
                                        <span class="uc_button_app">Xem nhanh</span>
                                    </a>
                                </div>
                            <!-- end of simple app download buttons -->
                            </div>
                            <img class="uc_avatar" src="img/icon-human/1.jpg" alt="avatar"/>
                        </div>
                        <!-- end of customer review box --> 
                        <!-- start of customer review box -->
                        <div class="uc_customer_review_box">
                            <span class="uc_content">In sit cras, vel auctor eu augue! Ut, nec vel adipiscing? Amet pulvinar, nascetur sed vut nunc! Scelerisque mus in. Enim, nec penatibus augue, et arcu! Cursus odio! Montes porttitor lectus!</span>
                            <div class="left-box ">

                                <p class="uc_name">Rafael Oliveira</p>
                                <p class="uc_job">CEO - Rafael Oliveira Design</p>
                            </div>
                            <div class="right-box pull-right">
                                <!-- start of simple app download buttons -->
                                <div class="uc_simple_app_download_buttons">
                                    <a href="" class="uc_app_button">
                                        <i class="fa fa-download" aria-hidden="true"></i>
                                        <span class="uc_button_app">Tải xuống </span>
                                    </a>
                                    <a href="" class="uc_app_button">
                                        <i class="fa fa-eye" aria-hidden="true"></i>
                                        <span class="uc_button_app">Xem nhanh</span>
                                    </a>
                                </div>
                            <!-- end of simple app download buttons -->
                            </div>
                            <img class="uc_avatar" src="img/icon-human/1.jpg" alt="avatar"/>
                        </div>
                        <!-- end of customer review box --> 
                    </div>
                </div>
                <div class="col-md-5 block first col-sm-12">
                    <div class="search">
                        <input type="text" class="form-control input-search" maxlength="64" placeholder="Tìm kiếm" />
                        <button type="submit" class="btn btn-primary btn-search"><i class="fa fa-search"></i><p>Tìm kiếm</p></button>
                    </div>
                </div>
                <div class="col-md-5 block col-sm-12">
                    <div class="contact_info">
                        <p  class="title-default">Công văn cũ hơn</p>
                        <!-- start of clean accordion -->
                        <div class="uc_clean_accordion">
                            <div class="uc_clean_accordion_wrap">
                                <div id="accor-congvan" class="uc_clean_accorder_content">
                                    <!-- start of line 1 -->
                                    <h3 class="uc_head_line">
                                       <a href="" class="uc_link_tittle">Công văn tháng 4</a>
                                    </h3>
                                    <div class="uc_line_content">
                                       <p class="cv_p">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo<span><a href=""class="download_link"><i class="fa fa-download"></i></a>|<a><i class="fa fa-eye"></i></a></span></p>
                                        <p class="cv_p">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium 2<span><a href=""class="download_link"><i class="fa fa-download"></i></a>|<a><i class="fa fa-eye"></i></a></span></p>
                                        <p class="cv_p">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium 3<span><a href=""class="download_link"><i class="fa fa-download"></i></a>|<a><i class="fa fa-eye"></i></a></span></p>
                                        
                                    </div>
                                    <!-- end of line 1 -->

                                    <!-- start of line 2 -->
                                    <h3 class="uc_head_line">
                                        <a href="" class="uc_link_tittle">Công văn tháng 3</a>
                                    </h3>
                                    <div class="uc_line_content">
                                        <p class="uc_des">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.</p>
                                    </div>
                                    <!-- end of line 2 -->

                                    <!-- start of line 3 -->
                                    <h3 class="uc_head_line">
                                        <a href="" class="uc_link_tittle">Công văn tháng 2</a>
                                    </h3>
                                    <div class="uc_line_content">
                                        <p class="uc_des">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.</p>
                                    </div>
                                    <!-- end of line 3 -->

                                    <!-- start of line 4 -->
                                    <h3 class="uc_head_line">
                                        <a href="" class="uc_link_tittle">Công văn tháng 1</a>
                                    </h3>
                                    <div class="uc_line_content">
                                        <p class="uc_des">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.</p>
                                    </div>
                                    <!-- end of line 4 -->
                                </div>
                            </div>
                        </div>
                        <!-- end of clean accordion -->
                    </div>
                </div>
                
            </div>
        
    </div>