<?php
$urlCSS_DSDN = URL_TEMPLATE . '/frontend_dsdn/css';
$urlJS_DSDN = URL_TEMPLATE . '/frontend_dsdn/js';
$urlImage_DSDN = URL_TEMPLATE . '/frontend_dsdn/img';

use Zend\Session\Container;

$ssSystem = new Container('system');
$helperString = new \Ocoder\Helper\String;

$featuredProducts = $this->featuredProducts;
?>

<div class="container topslider">
        <div class="flexslider">
            <ul class="slides">
             <?php 
            $isFirst = true; 
            foreach ($this->banners as $banner) { 
                if ($ssSystem->language == DEFAULT_LANGUAGE) {
                    $name = $banner->name;
                    $description = $banner->description;
                } else {
                    $nameLang = json_decode($banner->name_lang);
                    $nameField = 'name_' . $ssSystem->language;
                    $name = $nameLang->$nameField;
                    $descritionLang = json_decode($banner->descrition_lang);
                    $descritionField = 'descrition_' . $ssSystem->language;
                    $descrition = $descritionLang->$descritionField;
                }
                $classActive = $isFirst ? 'active' : '';
                $isFirst = false;
                ?>
                <li><img src="<?php echo URL_APPLICATION . $banner->banner ?>" alt="<?php echo $name; ?>"/></li>
            <?php } ?>    
            </ul>
        </div>
    </div>
    <div class="container page-home page-default">
        <div class="content">
            <div id="text-6" class="widget_text">
                <div class="textwidget">
                    <div class="sub-slider row">
                        <div class="col-xs-10 col-sm-10 col-sm-offset-1 col-xs-offset-2">
                            <div class="row">
                                <div class="slide-item col-sm-3 col-xs-5 ">
                                    <div class="uc_background_image_content_box" id="orange">
                                        <a href="<?php echo URL_APPLICATION.'/bv/cung-cap-thiet-bi-1'?>" class="uc_item_link">
                                            <!-- start of box content block -->
                                            <div class="uc_banner_box">
                                                <img src="<?php echo $urlImage_DSDN ?>/services/orange_train.jpg" alt="tàu hỏa " class="uc_item_img"/>
                                                <!-- overplay block -->
                                                <div class="overplay"></div>
                                                <div class="uc_item_html">
                                                    <h2 class="uc_item_tittle">Cung cấp thiết bị</h2>
                                                   <button class="uc_add_cart">
                                                        <span class="uc_link_add">Xem chi tiết!</span>
                                                    </button>
                                                </div>
                                            </div>
                                            <!-- end of box content block -->
                                        </a>
                                    </div>
                                    <!-- end of background image content box-->
                                </div>
                                <div class="slide-item col-sm-3 col-xs-5">
                                    <div class="uc_background_image_content_box" id="green">
                                        <a href="<?php echo URL_APPLICATION.'/bv/bao-tri-van-hanh-2'?>" class="uc_item_link">
                                            <!-- start of box content block -->
                                            <div class="uc_banner_box">
                                                <img src="<?php echo $urlImage_DSDN ?>/services/green-train.jpg" alt="tàu hỏa " class="uc_item_img"/>
                                                <div class="overplay"></div>
                                                <div class="uc_item_html">
                                                    <h2 class="uc_item_tittle">Bảo trì-Vận hành</h2>
                                                    <button class="uc_add_cart">
                                                        <span class="uc_link_add">Xem chi tiết!</span>
                                                    </button>
                                                </div>
                                            </div>
                                            <!-- end of box content block -->
                                        </a>
                                    </div>
                                    <!-- end of background image content box-->
                                </div>
                                <div class="slide-item col-sm-3 col-xs-5 ">
                                    <div class="uc_background_image_content_box" id="blue">
                                        <a href="<?php echo URL_APPLICATION.'/bv/tu-van-thiet-ke-6'?>" class="uc_item_link">
                                            <!-- start of box content block -->
                                            <div class="uc_banner_box">
                                                <img src="<?php echo $urlImage_DSDN ?>/services/blue_train.jpg" alt="tàu hỏa " class="uc_item_img"/>
                                                <div class="overplay"></div>
                                                <div class="uc_item_html">
                                                    <h2 class="uc_item_tittle">Tư vấn thiết kế</h2>
                                                    <button class="uc_add_cart">
                                                        <span class="uc_link_add">Xem chi tiết!</span>
                                                    </button>
                                                </div>
                                            </div>
                                            <!-- end of box content block -->
                                        </a>
                                    </div>
                                    <!-- end of background image content box-->
                                </div>
                                <div class="slide-item col-sm-3 col-xs-5">
                                    <div class="uc_background_image_content_box" id="sky">
                                        <a href="<?php echo URL_APPLICATION.'/bv/cac-dich-vu-khac-7'?>" class="uc_item_link">
                                            <!-- start of box content block -->
                                            <div class="uc_banner_box">
                                                <img src="<?php echo $urlImage_DSDN ?>/services/yellow-train.jpg" alt="tàu hỏa " class="uc_item_img"/>
                                                <div class="overplay"></div>
                                                <div class="uc_item_html">
                                                    <h2 class="uc_item_tittle">Dịch vụ khác</h2>
                                                    <button class="uc_add_cart">
                                                        <span class="uc_link_add">Xem chi tiết!</span>
                                                    </button>
                                                </div>
                                            </div>
                                            <!-- end of box content block -->
                                        </a>
                                    </div>
                                    <!-- end of background image content box-->
                                </div>
                               
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="container">
                    <div class="image_background"></div>
                    <div id="text-7" class="widget_text">
                        <div class="textwidget">
                            <div class="main-content-wrap col-md-9 col-sm-12">
                                
                                <div class="page-content row">
                                    <div class="content-wrap col-md-7">
                                        <h2 class="title-default ">Giới thiệu chung</h2>
                                        <div class="p-default">
                                            <?php echo $ssSystem->configs->company_description;?>
                                        </div>
                                        
                                        <div class="uc_clean_accordion">
                                            <div class="uc_clean_accordion_wrap">
                                                <div id="accordion" class="uc_clean_accorder_content">
                                                    <!-- start of line 1 -->
                                                    <h3 class="uc_head_line">
                                                       <a href="" class="uc_link_tittle sub-title-default"><?php echo COMPANY_HISTORY?></a>
                                                    </h3>
                                                    <div class="uc_line_content">
                                                        <div class="uc_des p-default">
                                                        
                                                        <?php echo $ssSystem->configs->company_history;?>
                                                        </div>
                                                    </div>
                                                    <!-- end of line 1 -->

                                                    <!-- start of line 2 -->
                                                    <h3 class="uc_head_line">
                                                        <a href="" class="uc_link_tittle sub-title-default">Ngành nghề kinh doanh</a>
                                                    </h3>
                                                    <div class="uc_line_content">
                                                        <div class="uc_des p-default">
                                                            <?php echo $ssSystem->configs->company_business;?>
                                                        </div>
                                                        
                                                    </div>
                                                    <!-- end of line 2 -->
                                                </div>
                                            </div>
                                        </div>
                                        <!-- end of clean accordion -->
                                    </div>
                                    <div class="col-md-5 block ">
                                        <div class="search padding_right5">
                                            <form action="<?php echo URL_APPLICATION . '/tim-kiem/' ?>" method="GET">
                                                <input type="text" class="form-control input-search" id="keyword-search" maxlength="64" name='tk' placeholder="<?php echo SEARCH ?>" value="<?php echo array_key_exists('tk', $_GET) ? $_GET['tk'] : '' ?>" />
                                                <button type="submit" class="btn btn-primary btn-search"><i class="fa fa-search"></i><p><?php echo SEARCH ?></p></button>
                                            </form>
                                        </div>
                                    </div>
                                    <div class="col-md-5 block">
                                        
                                        <?php $this->blkLatestNews(); ?>

                                    </div>
                                    <div class="col-md-5 block">
                                        <?php echo $this->blkVideo(); ?>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3 col-sm-12">
                                <div class="sidebar-left">
                                    <!--<div class="block login">
                                        <span>ĐĂNG NHẬP</span>
                                        <div>
                                            <form action="" method="post">
                                                <label for="acount">Tài khoản</label>
                                                <input id="acount" type="text" />
                                                <label for="pass">Mật khẩu</label>
                                                <input id="pass" type="text" />
                                                <button type="submit">Đăng nhập</button>
                                                <a href="#">Quên mật khẩu?</a>
                                            </form>
                                        </div>
                                    </div>-->
                                    

                                    <div class="menu-left-2 block">
                                        <h2 class="title-default">Văn phòng điều hành</h2>
                                        <ul class="menu-list">
                                            <li class="sub-title-default"><?php echo $ssSystem->configs->company_name; ?></li>
                                            <li class="sub-title-default"><?php echo $ssSystem->configs->company_address; ?></li>
                                            
                                        </ul>
                                    </div>

                                    <div class="menu-left-3 block">
                                        <h2 class="title-default">LIÊN KẾT KHÁC</h2>
                                        <div class="wrap">
                                            <li class="sub-title-default"><a href="#" target="_blank">Tổng công ty đường sắt Việt Nam</a></li>
                                            <li class="sub-title-default"><a href="#" target="_blank">Công ty tín hiệu đường sắt Hà Nội</a></li>
                                            <li class="sub-title-default"><a href="#" target="_blank">Công ty thông tin tín hiệu đường sắt Đà Nẵng</a></li>
                                            <li class="sub-title-default"><a href="#" target="_blank">Công ty thông tin tín hiệu đường sắt Sài Gòn</a></li>
                                            <li class="sub-title-default"><a href="#" target="_blank">Báo điện tử VnExpress</a></li>
                                            <li class="sub-title-default"><a href="#" target="_blank">Báo điện tử Dân trí</a></li> 
                                        </div>
                                        
                                    </div>
                                    <div class="block">
                                        <a href="http://www.accuweather.com/vi/vn/da-nang/352954/weather-forecast/352954" class="aw-widget-legal">

                                        </a><div id="awcc1465456113431" class="aw-widget-current"  data-locationkey="2-352954_1_AL" data-unit="c" data-language="vi" data-useip="false" data-uid="awcc1465456113431"></div>
                                        <script type="text/javascript" src="http://oap.accuweather.com/launch.js"></script>
                                    </div> 
                                    <div class="menu-left-1 block">
                                        <h2 class="title-default">THỐNG KÊ LƯỢNG TRUY CẬP</h2>
                                        <ul class="menu-list">
                                            <li class="sub-title-default"><i class="fa fa-users"></i> Đang truy cập : 17</li>
                                            <li class="sub-title-default"><i class="fa fa-newspaper-o"></i> Truy cập hôm nay : 45</li>
                                            <li class="sub-title-default"><i class="fa fa-calendar-o"></i> Truy cập trong tháng : 1023</li>
                                            <li class="sub-title-default"><i class="fa fa-bar-chart"></i> Tổng lượt truy cập : 56875</li>
                                            
                                        </ul>
                                    </div>
                                    <!-- END .menu-left-1 --> 
                                </div>
                                
                                
                                <!-- END .menu-left-2 -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <span class="title-default partner">CÁC ĐỐI TÁC</span>
            <div>
            <?php echo $this->blkPartners(); ?>
                <!-- start of customer logo carousel -->
                
                <!-- end of customer logo carousel -->
            </div>
        </div>
    </div>
    