<?php
$urlCSS_DSDN = URL_TEMPLATE . '/frontend_dsdn/css';
$urlJS_DSDN = URL_TEMPLATE . '/frontend_dsdn/js';
$urlImage_DSDN = URL_TEMPLATE . '/frontend_dsdn/img';
?>

<?php echo $this->doctype(); ?>
<html>
    <head>
        <?php
        echo $this->headTitle();
        echo //$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')
//                $this->headMeta()->appendName('description', PAGE_TITLE)
                 $this->headMeta()->setCharset('utf-8');

        echo $this->headLink()->appendStylesheet(array(
                    'rel' => 'shortcut icon',
                    'type' => 'image/x-icon',
                    'href' => $urlImage_DSDN . '/favicon.ico'
                        ), 'PREPEND')
                ->appendStylesheet(URL_PUBLIC . '/css/bootstrap.min.css')

        // ->appendStylesheet($urlCSS . '/styles.less')
        ;

        echo '<link href="' . $urlCSS_DSDN . '/owl.carousel.css" rel="stylesheet/less">';
        echo '<link href="' . $urlCSS_DSDN . '/style.css" rel="stylesheet/less">';
        echo '<link href="' . $urlCSS_DSDN . '/responsive.css" rel="stylesheet/less">';
        echo '<link href="' . $urlCSS_DSDN . '/background_image_content_box.css" rel="stylesheet/less">';
        echo '<link href="' . $urlCSS_DSDN . '/team_member_hover_effect.css" rel="stylesheet/less">';
        echo '<link href="' . $urlCSS_DSDN . '/clean_accordion.css" rel="stylesheet/less">';
        echo '<link href="' . $urlCSS_DSDN . '/minimal_logo_carousel.css" rel="stylesheet/less">';
        echo '<link href="' . $urlCSS_DSDN . '/flexslider.css" rel="stylesheet/less">';
        echo '<link href="' . $urlCSS_DSDN . '/customer_review_box.css" rel="stylesheet/less">';
        echo '<link href="' . $urlCSS_DSDN . '/simple_app_download_buttons.css" rel="stylesheet/less">';
        echo '<link href="' . $urlCSS_DSDN . '/bootstrap.css" rel="stylesheet/less">';
        echo '<link href="' . $urlCSS_DSDN . '/contact.css" rel="stylesheet/less">';
        echo '<link href="' . $urlCSS_DSDN . '/member.css" rel="stylesheet/less">';
        echo '<link href="' . $urlCSS_DSDN . '/news_image.css" rel="stylesheet/less">';
        echo '<link href="' . $urlCSS_DSDN . '/magnific-popup.css" rel="stylesheet/less">';

        echo $this->headScript()->appendFile($urlJS_DSDN . '/bootstrap.js')
                ->appendFile($urlJS_DSDN . '/jquery.js')
                ->appendFile($urlJS_DSDN . '/jquery.flexslider-min.js')
                ->appendFile($urlJS_DSDN . '/jquery.magnific-popup.min.js');
        echo '<script src="https://code.jquery.com/jquery-1.11.2.js"   integrity="sha256-WMJwNbei5YnfOX5dfgVCS5C4waqvc+/0fV7W2uy3DyU="   crossorigin="anonymous"></script>';
        ?>	

    </head>
    <body>
        <?php //echo $this->blkConfigs() ?>
        <div class="body-wrapper container">
            <!-- Header of Website -->
            <header class="navbar navbar-static-top bs-docs-nav" id="top" role="banner">
                <?php include_once 'includes/header.phtml'; ?>
            </header> <!-- End Header of Website -->

            <?php echo $this->content; ?>

            <?php include_once 'includes/footer.phtml'; ?>
        </div>
    </body>
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-59438542-1', 'auto');
    ga('send', 'pageview');
    </script>
</html>