<?php
$urlCSS_DSDN = URL_TEMPLATE . '/frontend_dsdn/css';
$urlJS_DSDN = URL_TEMPLATE . '/frontend_dsdn/js';
$urlImage_DSDN = URL_TEMPLATE . '/frontend_dsdn/img';
?>
<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <?php
        $this->headMeta()->setCharset('utf-8');
        echo $this->headTitle();
        echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
//                $this->headMeta()->appendName('description', PAGE_TITLE)
        echo $this->headLink()->appendStylesheet(array(
                    'rel' => 'shortcut icon',
                    'type' => 'image/x-icon',
                    'href' => $urlImage_DSDN . '/favicon.ico'
                        ), 'PREPEND')
                ->appendStylesheet($urlCSS_DSDN .'/bootstrap.css')
                ->appendStylesheet($urlCSS_DSDN .'/owl.carousel.css')
                ->appendStylesheet($urlCSS_DSDN .'/responsive.css')
                ->appendStylesheet($urlCSS_DSDN .'/style.css')
                ->appendStylesheet($urlCSS_DSDN .'/background_image_content_box.css')
                ->appendStylesheet($urlCSS_DSDN .'/team_member_hover_effect.css')
                ->appendStylesheet($urlCSS_DSDN .'/clean_accordion.css')
                ->appendStylesheet($urlCSS_DSDN .'/customer_logo_carousel.css')
                ->appendStylesheet($urlCSS_DSDN .'/minimal_logo_carousel.css')
                ->appendStylesheet($urlCSS_DSDN .'/clean_accordion.css')
                ->appendStylesheet($urlCSS_DSDN .'/flexslider.css')
                ->appendStylesheet($urlCSS_DSDN .'/customer_review_box.css')
                ->appendStylesheet($urlCSS_DSDN .'/simple_app_download_buttons.css')
                ->appendStylesheet($urlCSS_DSDN .'/contact.css')
                ->appendStylesheet($urlCSS_DSDN .'/member.css')
                ->appendStylesheet($urlCSS_DSDN .'/news_image.css')
                ->appendStylesheet($urlCSS_DSDN .'/magnific-popup.css')
        // ->appendStylesheet($urlCSS . '/styles.less')
        ;
        echo '<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css" />
    ';
        echo '<script src="https://code.jquery.com/jquery-1.11.2.js"   integrity="sha256-WMJwNbei5YnfOX5dfgVCS5C4waqvc+/0fV7W2uy3DyU="   crossorigin="anonymous"></script>';
        echo $this->headScript()->appendFile($urlJS_DSDN . '/bootstrap.js')
                ->appendFile($urlJS_DSDN . '/jquery.js')
                ->appendFile($urlJS_DSDN . '/jquery.flexslider-min.js')
                ->appendFile($urlJS_DSDN . '/jquery.magnific-popup.min.js')
    ?>
</head>
<body>
    <!-- Docs master nav -->
    <?php include_once 'includes/header.phtml'; ?>
    <?php echo $this->content; ?>
    
    <?php include_once 'includes/footer.phtml'; ?>
</body>
</html>